import type { FishDef } from "./types";

// Четвёртый том кодекса: 70 видов, дополняющих все двенадцать акваторий
export const FISH_VOL4: FishDef[] = [
  // ───────────── ТИХАЯ БУХТА ─────────────
  { id: "black_goby", name: "Бычок-кнут", latin: "Mesogobius batrachocephalus", loc: ["bay"], depth: [3, 18], rarity: "common", time: "any", weight: [0.05, 0.4], price: 45, strength: 1, shape: "fusiform", colors: { body: "#4a4034", belly: "#a89a80", fin: "#2e281e" }, pattern: "spots", bait: ["worm", "mussel"], desc: "Самый крупный из черноморских бычков, с тёмной головой, похожей на лягушачью. Зимой уходит глубже остальных и первым возвращается весной." },
  { id: "sprat", name: "Тюлька", latin: "Clupeonella cultriventris", loc: ["bay", "estuary"], depth: [0, 10], rarity: "common", time: "any", season: [0, 2], weight: [0.005, 0.02], price: 500, strength: 1, shape: "fusiform", colors: { body: "#6a8a9a", belly: "#f0f4f4", fin: "#7a9aa6" }, pattern: "gradient", bait: ["worm", "shrimp"], desc: "Крошечная сельдь солоноватых вод. Весной и осенью стоит у берега такими плотными стаями, что вода кажется серебряной." },
  { id: "rainbow_wrasse", name: "Морская радужница", latin: "Coris julis", loc: ["bay"], depth: [2, 16], rarity: "uncommon", time: "day", weather: ["clear"], weight: [0.03, 0.2], price: 180, strength: 1, shape: "long", colors: { body: "#3a7a5a", belly: "#e8e0a0", fin: "#d85a3a", accent: "#e8a040" }, pattern: "stripes", bait: ["shrimp", "worm"], desc: "Узкая рыбка с оранжевой молнией вдоль бока. На ночь зарывается в песок и спит, выставив наружу только глаза." },
  { id: "sea_bream_bay", name: "Морской карась-зубарик", latin: "Diplodus puntazzo", loc: ["bay"], depth: [4, 18], rarity: "uncommon", time: "twilight", weight: [0.3, 1.8], price: 90, strength: 3, shape: "deep", colors: { body: "#a8a898", belly: "#eceae0", fin: "#6a6a5a", accent: "#2a2a24" }, pattern: "bars", bait: ["mussel", "shrimp"], desc: "Острое рыло и резцы, как у кролика. Соскребает мидий со свай и камней, поэтому охотнее всего берёт раскрытую ракушку." },
  { id: "sea_horse", name: "Морской конёк", latin: "Hippocampus guttulatus", loc: ["bay"], depth: [2, 12], rarity: "rare", time: "day", season: [1], weight: [0.01, 0.03], price: 3000, strength: 1, shape: "eel", colors: { body: "#9a7a4a", belly: "#c8a870", fin: "#6a5030", accent: "#e8d8a0" }, pattern: "spots", bait: ["shrimp"], desc: "Держится хвостом за стебли взморника и почти не двигается. Детёнышей вынашивает отец — в сумке на брюхе. Лучше отпустить." },
  { id: "bay_turbot_giant", name: "Калкан-великан", latin: "Scophthalmus maximus", loc: ["bay"], depth: [10, 18], rarity: "epic", time: "night", season: [2, 3], weight: [8, 20], price: 90, strength: 7, shape: "flat", colors: { body: "#5e5440", belly: "#ece6d0", fin: "#40382a", accent: "#8a7a58" }, pattern: "spots", bait: ["livebait", "cutbait"], desc: "Тюрбо размером с тележное колесо. Раз в несколько лет подходит к бухте осенними ночами, и тогда о нём говорят во всех трактирах." },

  // ───────────── ЛИМАН ─────────────
  { id: "roach", name: "Вобла", latin: "Rutilus caspicus", loc: ["estuary"], depth: [0, 8], rarity: "common", time: "day", weight: [0.1, 0.5], price: 70, strength: 2, shape: "fusiform", colors: { body: "#8a9a9a", belly: "#f0f0ea", fin: "#c85a3a" }, pattern: "gradient", bait: ["worm"], desc: "Родственница тарани, главная закуска приморских городов. Вяленую её вешают связками под навесами рыбачьих хижин." },
  { id: "bream", name: "Лещ", latin: "Abramis brama", loc: ["estuary"], depth: [3, 12], rarity: "common", time: "twilight", weight: [0.4, 4], price: 45, strength: 3, shape: "deep", colors: { body: "#8a7a4a", belly: "#d8c890", fin: "#4a4030" }, pattern: "none", bait: ["worm", "mussel"], desc: "Широкий, как поднос, и осторожный. Поклёвку выдаёт поплавок, который медленно ложится на бок." },
  { id: "rudd", name: "Краснопёрка", latin: "Scardinius erythrophthalmus", loc: ["estuary"], depth: [0, 4], rarity: "common", time: "day", season: [1], weight: [0.05, 0.4], price: 80, strength: 1, shape: "deep", colors: { body: "#a8a060", belly: "#f0e8c0", fin: "#e0402a" }, pattern: "gradient", bait: ["worm"], desc: "Золотистая рыбка с алыми плавниками, стоит у самой поверхности среди камыша. Летом берёт почти непрерывно." },
  { id: "asp", name: "Жерех", latin: "Leuciscus aspius", loc: ["estuary"], depth: [0, 8], rarity: "uncommon", time: "day", weight: [1, 6], price: 45, strength: 5, shape: "fusiform", colors: { body: "#6a7a84", belly: "#eceef0", fin: "#8a6a5a" }, pattern: "gradient", bait: ["spoon", "wobbler"], desc: "Единственный хищник среди карповых. Бьёт хвостом по мелочи у поверхности, оглушая её, и возвращается собрать добычу." },
  { id: "chekhon", name: "Чехонь", latin: "Pelecus cultratus", loc: ["estuary"], depth: [0, 6], rarity: "uncommon", time: "day", season: [0, 2], weight: [0.2, 0.9], price: 90, strength: 3, shape: "long", colors: { body: "#9aa8b0", belly: "#f4f6f6", fin: "#7a8a90" }, pattern: "gradient", bait: ["spoon", "worm"], desc: "Рыба-сабля с прямой спиной и выпуклым брюхом. Ходит стаями у поверхности и выпрыгивает за мошкой." },
  { id: "starry_sturgeon", name: "Севрюга", latin: "Acipenser stellatus", loc: ["estuary"], depth: [5, 12], rarity: "rare", time: "night", season: [0], weight: [4, 15], price: 110, strength: 6, shape: "long", colors: { body: "#6a6a60", belly: "#e0dcd0", fin: "#4a4a44", accent: "#e8e4d8" }, pattern: "spots", bait: ["worm", "mussel"], desc: "Осётр с узким, как шпага, рылом и звёздчатыми костяными щитками. Идёт в реки только весенними ночами." },

  // ───────────── СКАЛИСТЫЙ МЫС ─────────────
  { id: "comber", name: "Каменный окунь", latin: "Serranus cabrilla", loc: ["cape"], depth: [5, 40], rarity: "common", time: "day", weight: [0.1, 0.6], price: 75, strength: 2, shape: "fusiform", colors: { body: "#b86a4a", belly: "#f0d0b0", fin: "#c8804a", accent: "#4a6aa0" }, pattern: "bars", bait: ["shrimp", "worm"], desc: "Небольшой пёстрый окунь каменистых склонов. Каждая особь одновременно самец и самка — редкость даже среди рыб." },
  { id: "pollack_yellow", name: "Люр", latin: "Pollachius pollachius", loc: ["cape"], depth: [10, 45], rarity: "uncommon", time: "twilight", weight: [1, 8], price: 55, strength: 5, shape: "fusiform", colors: { body: "#7a6a3a", belly: "#e8e0c0", fin: "#5a4a28" }, pattern: "gradient", bait: ["jig", "livebait", "spoon"], desc: "Бронзовая треска подводных скал. Стоит над обрывом и бросается вверх на всё, что блестит." },
  { id: "red_scorpion", name: "Красная скорпена", latin: "Scorpaena scrofa", loc: ["cape"], depth: [20, 45], rarity: "rare", time: "night", weight: [0.5, 3], price: 140, strength: 4, shape: "deep", colors: { body: "#c8402a", belly: "#f0a080", fin: "#8a2a1a", accent: "#f0d0a0" }, pattern: "spots", bait: ["livebait", "shrimp"], desc: "Главная рыба для настоящей буйабеса. Кожные лоскуты на голове делают её неотличимой от поросшего камня." },
  { id: "spurdog_giant", name: "Морская лисица", latin: "Alopias vulpinus", loc: ["cape", "ocean"], depth: [10, 200], rarity: "epic", time: "day", season: [1], weight: [80, 250], price: 7, strength: 9, shape: "shark", colors: { body: "#5a5a6a", belly: "#eaeaf0", fin: "#40404c" }, pattern: "gradient", bait: ["livebait", "squid"], desc: "Хвост длиной с тело. Им лисья акула, как кнутом, глушит стаю скумбрии, а потом собирает оглушённых." },

  // ───────────── ШХЕРЫ ─────────────
  { id: "ide", name: "Язь", latin: "Leuciscus idus", loc: ["skerries"], depth: [0, 10], rarity: "common", time: "twilight", weight: [0.4, 3], price: 50, strength: 3, shape: "fusiform", colors: { body: "#8a8060", belly: "#e8e0c8", fin: "#c85a3a" }, pattern: "none", bait: ["worm", "shrimp"], desc: "Золотисто-серебряный, крепкий и осторожный. В тёплые вечера выходит из тростника к каменным плитам островов." },
  { id: "vendace", name: "Ряпушка", latin: "Coregonus albula", loc: ["skerries"], depth: [5, 40], rarity: "common", time: "any", season: [2, 3], weight: [0.03, 0.2], price: 180, strength: 1, shape: "fusiform", colors: { body: "#7a8a9a", belly: "#f0f4f4", fin: "#6a7a8a" }, pattern: "gradient", bait: ["shrimp", "worm"], desc: "Маленький сиг холодных проливов. Икру ряпушки на севере называют «морским золотом»." },
  { id: "garfish_baltic", name: "Колюшка трёхиглая", latin: "Gasterosteus aculeatus", loc: ["skerries"], depth: [0, 6], rarity: "common", time: "day", season: [0, 1], weight: [0.002, 0.008], price: 2400, strength: 1, shape: "fusiform", colors: { body: "#6a7a5a", belly: "#e04a3a", fin: "#8a9a7a", accent: "#4a8ab0" }, pattern: "bars", bait: ["worm"], desc: "Крошечная рыбка с тремя шипами. Весной самец краснеет брюхом, строит из водорослей гнездо и охраняет его от всех." },
  { id: "burbot", name: "Налим", latin: "Lota lota", loc: ["skerries"], depth: [10, 70], rarity: "uncommon", time: "night", season: [3], weight: [0.5, 5], price: 70, strength: 4, shape: "eel", colors: { body: "#5a5030", belly: "#c8c0a0", fin: "#3a3420" }, pattern: "spots", bait: ["worm", "cutbait"], desc: "Единственная пресноводная треска. Самый активный в лютые морозы, а летом впадает в спячку под корягами." },
  { id: "zander_baltic", name: "Берш", latin: "Sander volgensis", loc: ["skerries"], depth: [4, 30], rarity: "uncommon", time: "night", weight: [0.3, 1.8], price: 70, strength: 4, shape: "fusiform", colors: { body: "#7a8468", belly: "#e8e8dc", fin: "#5a6448", accent: "#2a3020" }, pattern: "bars", bait: ["jig", "livebait"], desc: "Младший родственник судака без клыков и с широкими тёмными полосами. Держится стайками у свалов солоноватых проливов." },
  { id: "wels_skerry", name: "Нельма", latin: "Stenodus leucichthys", loc: ["skerries"], depth: [10, 60], rarity: "rare", time: "any", season: [2, 3], weight: [2, 10], price: 190, strength: 5, shape: "fusiform", colors: { body: "#4a6070", belly: "#f0f4f6", fin: "#34485a", accent: "#c8d4dc" }, pattern: "gradient", bait: ["jig", "livebait"], desc: "Единственный хищник среди сиговых — с большой пастью и серебряной бронёй чешуи. Осенью заходит в опреснённые проливы шхер." },
  { id: "sea_eagle_trout", name: "Кумжа-танцовщица", latin: "Salmo labrax", loc: ["skerries"], depth: [0, 25], rarity: "epic", time: "twilight", weather: ["fog", "rain"], weight: [6, 14], price: 95, strength: 8, shape: "fusiform", colors: { body: "#5a6a6a", belly: "#ece8d8", fin: "#3a4a4a", accent: "#c04a3a" }, pattern: "spots", bait: ["wobbler", "spoon"], desc: "Редкая морская форель с красными крапинками вдоль боковой линии. На крючке выписывает над водой пируэты, за что и получила имя." },

  // ───────────── СЕВЕРНЫЙ ФЬОРД ─────────────
  { id: "saithe_black", name: "Норвежская бельдюга", latin: "Zoarces viviparus", loc: ["fjord"], depth: [20, 140], rarity: "common", time: "any", weight: [0.1, 0.5], price: 60, strength: 2, shape: "eel", colors: { body: "#6a6040", belly: "#c8bc98", fin: "#4a4228" }, pattern: "spots", bait: ["worm", "cutbait"], desc: "Живородящая рыба-угорь: мальки появляются на свет полностью сформированными. Кости у неё зеленеют при варке." },
  { id: "norway_haddock", name: "Норвежский макрурус", latin: "Macrourus berglax", loc: ["fjord"], depth: [100, 160], rarity: "uncommon", time: "any", weight: [0.5, 3], price: 70, strength: 3, shape: "long", colors: { body: "#6a6a6a", belly: "#9a9a9a", fin: "#4a4a4a" }, pattern: "none", bait: ["cutbait", "shrimp"], desc: "Долгохвост с шипастой чешуёй. На дне фьорда выискивает червей и мелких рачков." },
  { id: "arctic_skate", name: "Звёздчатый скат", latin: "Amblyraja radiata", loc: ["fjord"], depth: [40, 160], rarity: "uncommon", time: "any", weight: [1, 4], price: 40, strength: 4, shape: "ray", colors: { body: "#6a5a44", belly: "#f0ece0", fin: "#4a3e2e", accent: "#d8c8a0" }, pattern: "spots", bait: ["cutbait", "shrimp"], desc: "Небольшой скат с рядами острых шипов на спине. Самый обычный скат северных морей." },
  { id: "rabbit_chimaera", name: "Крапчатая химера", latin: "Hydrolagus affinis", loc: ["fjord"], depth: [120, 160], rarity: "rare", time: "night", weight: [2, 8], price: 110, strength: 4, shape: "long", colors: { body: "#7a6a64", belly: "#b8aca4", fin: "#5a4a44", accent: "#e8e0d8" }, pattern: "spots", bait: ["shrimp", "cutbait"], desc: "Большеглазая химера, выходящая из глубины только ночью. Её ядовитый шип на спине опаснее, чем кажется." },
  { id: "halibut_green", name: "Черный палтус", latin: "Reinhardtius hippoglossoides", loc: ["fjord"], depth: [100, 160], rarity: "epic", time: "any", season: [3, 0], weight: [8, 45], price: 45, strength: 8, shape: "flat", colors: { body: "#3a3a34", belly: "#6a6a60", fin: "#24241e" }, pattern: "none", bait: ["cutbait", "squid"], desc: "Камбала, которая плавает вертикально, как обычная рыба. Обе стороны тела у неё тёмные." },

  // ───────────── ТУМАННЫЙ БЕРЕГ ─────────────
  { id: "opaleye", name: "Опалоглаз", latin: "Girella nigricans", loc: ["kelp"], depth: [0, 16], rarity: "common", time: "day", weight: [0.3, 2], price: 45, strength: 3, shape: "deep", colors: { body: "#3a4a3a", belly: "#8a9a80", fin: "#2a3a2a", accent: "#e0e8f0" }, pattern: "spots", bait: ["mussel", "shrimp"], desc: "Тёмно-оливковая рыба с молочно-голубыми глазами. Щиплет водоросли в прибойной пене у самых скал." },
  { id: "rockfish_blue", name: "Синий морской окунь", latin: "Sebastes mystinus", loc: ["kelp"], depth: [5, 60], rarity: "common", time: "any", weight: [0.3, 2], price: 45, strength: 3, shape: "deep", colors: { body: "#3a4a6a", belly: "#8a9ab8", fin: "#2a3a5a" }, pattern: "spots", bait: ["shrimp", "jig"], desc: "Держится стаями над верхушками водорослей. Живёт до пятидесяти лет, а растёт так медленно, что каждая особь — старожил." },
  { id: "cabezon", name: "Кабезон", latin: "Scorpaenichthys marmoratus", loc: ["kelp"], depth: [3, 60], rarity: "uncommon", time: "any", weight: [1, 7], price: 45, strength: 5, shape: "angler", colors: { body: "#6a4a3a", belly: "#b89a80", fin: "#4a3228", accent: "#c8a060" }, pattern: "spots", bait: ["mussel", "shrimp"], desc: "Огромноголовый рогатковый бычок. Икра его ядовита, а мясо у многих особей голубоватое." },
  { id: "halibut_cali", name: "Калифорнийский палтус", latin: "Paralichthys californicus", loc: ["kelp"], depth: [5, 60], rarity: "uncommon", time: "twilight", weight: [2, 15], price: 45, strength: 5, shape: "flat", colors: { body: "#6a5a44", belly: "#ece8dc", fin: "#4a3e2e" }, pattern: "spots", bait: ["livebait"], desc: "Камбала-засадчик песчаных прогалин между водорослями. Бросается на живца с такой силой, что подпрыгивает над дном." },
  { id: "wolf_eel", name: "Волчий угорь", latin: "Anarrhichthys ocellatus", loc: ["kelp"], depth: [10, 140], rarity: "rare", time: "night", weight: [4, 18], price: 60, strength: 7, shape: "eel", colors: { body: "#6a6a64", belly: "#a8a8a0", fin: "#4a4a44" }, pattern: "spots", bait: ["mussel", "squid"], desc: "С мордой старика и челюстями, дробящими крабов. Пары живут в одной норе всю жизнь." },
  { id: "sevengill", name: "Семижаберная акула", latin: "Notorynchus cepedianus", loc: ["kelp"], depth: [10, 140], rarity: "rare", time: "night", weather: ["fog", "cloudy"], weight: [30, 110], price: 12, strength: 8, shape: "shark", colors: { body: "#6a6460", belly: "#c8c0b8", fin: "#4a4440" }, pattern: "spots", bait: ["cutbait", "squid"], desc: "Древняя акула с семью жаберными щелями. Охотится стаей на тюленей в туманных бухтах." },
  { id: "kelp_leviathan", name: "Хранитель леса", latin: "Stereolepis gigas senex", loc: ["kelp"], depth: [20, 60], rarity: "legendary", time: "night", moon: "full", weight: [250, 350], price: 18, strength: 10, shape: "deep", colors: { body: "#2a2a28", belly: "#6a6a64", fin: "#1a1a18", accent: "#c8c8b8" }, pattern: "spots", bait: ["livebait", "squid"], desc: "Гигантский окунь, которому, говорят, больше века. Выплывает из водорослевого леса лишь в полнолуние." },

  // ───────────── КОРАЛЛОВЫЙ РИФ ─────────────
  { id: "damselfish", name: "Помацентр", latin: "Chromis viridis", loc: ["reef"], depth: [0, 12], rarity: "common", time: "day", weight: [0.005, 0.02], price: 1500, strength: 1, shape: "deep", colors: { body: "#60d0b0", belly: "#a0f0d8", fin: "#40b090" }, pattern: "gradient", bait: ["shrimp"], desc: "Облако бирюзовых рыбок над ветвистым кораллом. При опасности все разом ныряют в ветки." },
  { id: "goatfish_yellow", name: "Жёлтая барабулька", latin: "Mulloidichthys vanicolensis", loc: ["reef"], depth: [2, 30], rarity: "common", time: "day", weight: [0.1, 0.6], price: 100, strength: 2, shape: "fusiform", colors: { body: "#f0d060", belly: "#fff0c0", fin: "#e0b030" }, pattern: "stripes", bait: ["shrimp", "worm"], desc: "Роется усиками в песке рифовых прогалин. За ней всегда следуют другие рыбы, подбирая то, что она вспугнула." },
  { id: "hawkfish", name: "Рыба-ястреб", latin: "Oxycirrhites typus", loc: ["reef"], depth: [10, 50], rarity: "uncommon", time: "day", weight: [0.01, 0.05], price: 1800, strength: 1, shape: "long", colors: { body: "#f0f0e8", belly: "#ffffff", fin: "#d84030", accent: "#d84030" }, pattern: "spots", bait: ["shrimp"], desc: "Длиннорылая рыбка в красную клетку. Сидит на веерных кораллах, как ястреб на ветке, и высматривает добычу." },
  { id: "bluefin_jack", name: "Радужная элагата", latin: "Elagatis bipinnulata", loc: ["reef", "ocean"], depth: [0, 40], rarity: "uncommon", time: "day", weight: [2, 12], price: 30, strength: 6, shape: "fusiform", colors: { body: "#3a70a0", belly: "#f0e8a0", fin: "#e0c040", accent: "#40a0e0" }, pattern: "stripes", bait: ["spoon", "wobbler"], desc: "Две голубые полосы вдоль тела и жёлтый хвост. Проносится над краем рифа стаей, будто торпеды." },
  { id: "coral_trout", name: "Коралловая форель", latin: "Plectropomus leopardus", loc: ["reef"], depth: [5, 50], rarity: "rare", time: "twilight", weight: [1, 8], price: 90, strength: 5, shape: "fusiform", colors: { body: "#d8402a", belly: "#f0a080", fin: "#b8301a", accent: "#50b0f0" }, pattern: "spots", bait: ["livebait", "shrimp"], desc: "Алый групер в голубых крапинках. Одна из самых дорогих рыб на азиатских рынках." },
  { id: "manta", name: "Манта", latin: "Mobula birostris", loc: ["reef"], depth: [5, 60], rarity: "epic", time: "day", weather: ["clear"], weight: [300, 1200], price: 2, strength: 9, shape: "ray", colors: { body: "#1a1e28", belly: "#f0f0f0", fin: "#101418", accent: "#e8e8e8" }, pattern: "spots", bait: ["shrimp"], desc: "Морской дьявол размахом до семи метров. Фильтрует планктон и позволяет себя разглядывать — снимать с крючка нужно бережно." },

  // ───────────── МАНГРОВЫЕ ПРОТОКИ ─────────────
  { id: "mojarra", name: "Мохарра", latin: "Eucinostomus argenteus", loc: ["mangrove"], depth: [0, 6], rarity: "common", time: "day", weight: [0.03, 0.2], price: 180, strength: 1, shape: "deep", colors: { body: "#c8ccd0", belly: "#f4f6f8", fin: "#a8acb0" }, pattern: "none", bait: ["worm", "shrimp"], desc: "Серебристая рыбка с выдвижным ртом-трубкой, которым высасывает рачков из ила." },
  { id: "sheepshead", name: "Архосарг", latin: "Archosargus probatocephalus", loc: ["mangrove"], depth: [1, 12], rarity: "common", time: "any", weight: [0.5, 5], price: 45, strength: 4, shape: "deep", colors: { body: "#c8c4b0", belly: "#ece8dc", fin: "#4a4840", accent: "#1a1a18" }, pattern: "bars", bait: ["mussel", "shrimp"], desc: "У неё почти человеческие зубы, которыми она крошит устриц на корнях мангров." },
  { id: "red_drum", name: "Красный горбыль", latin: "Sciaenops ocellatus", loc: ["mangrove"], depth: [0, 14], rarity: "uncommon", time: "twilight", weight: [2, 15], price: 35, strength: 6, shape: "fusiform", colors: { body: "#b86a3a", belly: "#f0d0b0", fin: "#8a4a2a", accent: "#1a1a1a" }, pattern: "none", bait: ["shrimp", "cutbait"], desc: "Медно-красный горбыль с чёрным пятном-обманкой у хвоста. Кормится на отмелях так мелко, что спина торчит над водой." },
  { id: "cubera", name: "Кубера", latin: "Lutjanus cyanopterus", loc: ["mangrove"], depth: [6, 16], rarity: "rare", time: "night", moon: "full", weight: [10, 50], price: 25, strength: 8, shape: "deep", colors: { body: "#6a4a44", belly: "#b89088", fin: "#4a3230" }, pattern: "none", bait: ["livebait", "cutbait"], desc: "Самый крупный луциан Атлантики. Собирается у устьев проток в полнолуние на нерест." },
  { id: "gar_tropical", name: "Тропический панцирник", latin: "Atractosteus tropicus", loc: ["mangrove"], depth: [0, 10], rarity: "uncommon", time: "day", weight: [1, 6], price: 50, strength: 5, shape: "long", colors: { body: "#6a6a40", belly: "#c8c090", fin: "#4a4a2a" }, pattern: "spots", bait: ["livebait", "spoon"], desc: "Древняя рыба в чешуе-броне, как у ископаемых. Может дышать атмосферным воздухом и греется у самой поверхности." },
  { id: "bull_shark", name: "Бычья акула", latin: "Carcharhinus leucas", loc: ["mangrove"], depth: [2, 16], rarity: "epic", time: "night", weather: ["rain", "storm"], weight: [90, 230], price: 7, strength: 10, shape: "shark", colors: { body: "#7a7a70", belly: "#eceae4", fin: "#5a5a52" }, pattern: "gradient", bait: ["livebait", "cutbait"], desc: "Единственная акула, способная жить в пресной воде. Заходит в протоки в ливень, когда вода мутная." },

  // ───────────── ОТКРЫТОЕ МОРЕ ─────────────
  { id: "bullet_tuna", name: "Пятнистый тунец", latin: "Auxis rochei", loc: ["ocean"], depth: [0, 80], rarity: "common", time: "day", weight: [0.5, 2], price: 40, strength: 4, shape: "fusiform", colors: { body: "#2a3a6a", belly: "#e0e6ee", fin: "#1a2a50", accent: "#1a1a3a" }, pattern: "bars", bait: ["spoon", "shrimp"], desc: "Самый маленький тунец, но стаи его тянутся на километры. Главная еда марлинов и парусников." },
  { id: "pompano_black", name: "Чёрная помфрета", latin: "Brama brama", loc: ["ocean"], depth: [50, 300], rarity: "common", time: "night", weight: [1, 4], price: 45, strength: 3, shape: "deep", colors: { body: "#3a3a44", belly: "#8a8a94", fin: "#2a2a30" }, pattern: "none", bait: ["squid", "cutbait"], desc: "Серебристо-чёрная рыба-лещ открытого океана. Ночью поднимается к поверхности вслед за кальмарами." },
  { id: "dolphinfish_pompano", name: "Малая корифена", latin: "Coryphaena equiselis", loc: ["ocean"], depth: [0, 40], rarity: "uncommon", time: "day", weight: [1, 5], price: 45, strength: 5, shape: "deep", colors: { body: "#40a070", belly: "#f0e050", fin: "#2a70c0" }, pattern: "spots", bait: ["wobbler", "spoon"], desc: "Младшая сестра махи-махи. Сопровождает плавучие брёвна и водоросли целыми стайками." },
  { id: "lancetfish", name: "Алепизавр", latin: "Alepisaurus ferox", loc: ["ocean"], depth: [100, 420], rarity: "rare", time: "night", weight: [2, 9], price: 60, strength: 5, shape: "long", colors: { body: "#6a7a8a", belly: "#b8c4cc", fin: "#3a3a4a", accent: "#1a1a2a" }, pattern: "none", bait: ["squid", "glow"], desc: "Парус на спине и клыки, как у дракона. Мышцы у него водянистые, зато желудок — настоящий музей глубоководных находок." },
  { id: "oilfish", name: "Масляная рыба", latin: "Ruvettus pretiosus", loc: ["ocean"], depth: [150, 420], rarity: "uncommon", time: "night", weight: [5, 30], price: 20, strength: 6, shape: "fusiform", colors: { body: "#4a3e32", belly: "#7a6a58", fin: "#2e261e" }, pattern: "none", bait: ["squid", "cutbait"], desc: "Жирная тёмная рыба сумеречной зоны. Чешуя у неё шершавая, как напильник." },
  { id: "shortfin_mako_giant", name: "Атлантический парусник", latin: "Istiophorus albicans", loc: ["ocean"], depth: [0, 90], rarity: "epic", time: "day", season: [1, 2], weight: [30, 60], price: 22, strength: 9, shape: "billfish", colors: { body: "#1a3a6a", belly: "#d8e0ec", fin: "#2a50a0", accent: "#9ac0f8" }, pattern: "spots", bait: ["livebait", "wobbler"], desc: "Атлантический родственник парусника: парус выше тела, а скорость — больше ста километров в час." },

  // ───────────── ВУЛКАНИЧЕСКИЙ АРХИПЕЛАГ ─────────────
  { id: "moorish_tang", name: "Жёлтый хирург", latin: "Zebrasoma flavescens", loc: ["volcano"], depth: [2, 25], rarity: "common", time: "day", weight: [0.05, 0.2], price: 500, strength: 1, shape: "deep", colors: { body: "#f8e030", belly: "#fff080", fin: "#f0d020" }, pattern: "none", bait: ["shrimp"], desc: "Лимонно-жёлтая рыбка, похожая на солнце. Стаями пасётся на молодых водорослях свежей лавы." },
  { id: "bigeye_scad", name: "Большеглазый ставрид", latin: "Selar crumenophthalmus", loc: ["volcano"], depth: [0, 80], rarity: "common", time: "night", weight: [0.1, 0.5], price: 90, strength: 2, shape: "fusiform", colors: { body: "#5a7a90", belly: "#eef2f4", fin: "#e0c040" }, pattern: "gradient", bait: ["shrimp", "spoon"], desc: "Огромные глаза и ночной образ жизни. На островах его ловят с лодок при свете фонарей." },
  { id: "lava_moray", name: "Лавовая мурена", latin: "Enchelycore pardalis", loc: ["volcano"], depth: [5, 60], rarity: "uncommon", time: "night", weight: [1, 4], price: 70, strength: 5, shape: "eel", colors: { body: "#c8602a", belly: "#f0a060", fin: "#8a3a1a", accent: "#f0f0e0" }, pattern: "spots", bait: ["squid", "cutbait"], desc: "Драконова мурена с рогами-ноздрями и изогнутыми челюстями. Живёт в трещинах застывшей лавы." },
  { id: "kampachi", name: "Кампачи", latin: "Seriola rivoliana", loc: ["volcano"], depth: [20, 200], rarity: "uncommon", time: "day", weight: [4, 25], price: 30, strength: 7, shape: "fusiform", colors: { body: "#7a7a60", belly: "#e8e4d0", fin: "#c8a040", accent: "#e0c050" }, pattern: "stripes", bait: ["jig", "livebait"], desc: "Янтарная сериола глубоких склонов. Бросается на джиг у самого дна и уводит его в скалы." },
  { id: "deepwater_snapper", name: "Эхутеа", latin: "Etelis carbunculus", loc: ["volcano"], depth: [150, 500], rarity: "rare", time: "any", weight: [2, 10], price: 70, strength: 5, shape: "fusiform", colors: { body: "#e84a4a", belly: "#f8c0c0", fin: "#c83030" }, pattern: "none", bait: ["squid", "jig"], desc: "Карминовый луциан кальдеры. Его поднимают с полукилометра, и он всё равно ярче любого рассвета." },
  { id: "pele_marlin", name: "Дочь Пеле", latin: "Makaira ignis", loc: ["volcano"], depth: [0, 250], rarity: "legendary", time: "day", weather: ["storm"], weight: [500, 750], price: 11, strength: 10, shape: "billfish", colors: { body: "#2a1a1a", belly: "#c8a090", fin: "#8a2a1a", accent: "#ff6a20" }, pattern: "bars", bait: ["livebait"], desc: "Марлин с огненными полосами на боках, которого островитяне считают посланницей богини вулкана. Приходит только в шторм." },

  // ───────────── БЕЗДНА ─────────────
  { id: "bristlemouth", name: "Щетинозуб", latin: "Cyclothone microdon", loc: ["abyss"], depth: [300, 1500], rarity: "common", time: "any", weight: [0.001, 0.005], price: 12000, strength: 1, shape: "long", colors: { body: "#2a2a30", belly: "#3a3a44", fin: "#1a1a20" }, pattern: "none", glow: "#80a0ff", bait: ["glow", "shrimp"], desc: "Самое многочисленное позвоночное на планете — их сотни триллионов. Размером с палец, с зубами, как щётка." },
  { id: "snipe_eel", name: "Угорь-бекас", latin: "Nemichthys scolopaceus", loc: ["abyss"], depth: [300, 2000], rarity: "uncommon", time: "any", weight: [0.02, 0.1], price: 1500, strength: 2, shape: "eel", colors: { body: "#6a5040", belly: "#8a7060", fin: "#4a3428" }, pattern: "none", bait: ["shrimp", "glow"], desc: "Тонкий, как шнурок, с челюстями, разведёнными как клюв птицы. Ловит креветок за усики." },
  { id: "fangtooth", name: "Саблезуб", latin: "Anoplogaster cornuta", loc: ["abyss"], depth: [500, 2000], rarity: "uncommon", time: "any", weight: [0.05, 0.2], price: 1200, strength: 2, shape: "deep", colors: { body: "#2a2224", belly: "#3a3034", fin: "#1a1416" }, pattern: "none", bait: ["glow", "shrimp"], desc: "Самые большие зубы относительно тела среди всех рыб. Чтобы закрыть пасть, прячет клыки в специальные карманы у мозга." },
  { id: "dragonfish_black", name: "Чёрный драконовый", latin: "Idiacanthus atlanticus", loc: ["abyss"], depth: [500, 2000], rarity: "rare", time: "night", weight: [0.05, 0.2], price: 2500, strength: 2, shape: "eel", colors: { body: "#101014", belly: "#1a1a20", fin: "#0a0a0c" }, pattern: "none", glow: "#ff4060", bait: ["glow"], desc: "Чернее чёрного — поглощает почти весь свет. Под глазами прячет красный прожектор, которого не видят другие рыбы." },
  { id: "abyss_octopus", name: "Осьминог-дамбо", latin: "Grimpoteuthis sp.", loc: ["abyss"], depth: [1000, 2000], rarity: "epic", time: "any", weather: ["fog", "cloudy"], weight: [1, 6], price: 600, strength: 3, shape: "squid", colors: { body: "#e8a8a0", belly: "#f0c8c0", fin: "#d88880" }, pattern: "none", bait: ["shrimp", "glow"], desc: "Плавники-уши, как у мультяшного слонёнка. Живёт глубже всех осьминогов мира и парит над дном, словно медуза." },

  // ───────────── ЛЕДЯНОЙ ШЕЛЬФ ─────────────
  { id: "emerald_rockcod", name: "Изумрудная нототения", latin: "Trematomus bernacchii", loc: ["antarctic"], depth: [0, 200], rarity: "common", time: "any", weight: [0.1, 0.5], price: 200, strength: 2, shape: "fusiform", colors: { body: "#6a5a3a", belly: "#c8b890", fin: "#4a3e28", accent: "#5a8a6a" }, pattern: "spots", bait: ["shrimp", "worm"], desc: "Пятнистая рыбка, лежащая на дне на грудных плавниках. Её сердце бьётся медленнее, чем у любой другой рыбы." },
  { id: "antarctic_eelpout", name: "Антарктический бельдюг", latin: "Pachycara brachycephalum", loc: ["antarctic"], depth: [200, 1000], rarity: "common", time: "any", weight: [0.2, 1], price: 150, strength: 2, shape: "eel", colors: { body: "#8a7a6a", belly: "#c8b8a8", fin: "#6a5a4a" }, pattern: "none", bait: ["cutbait", "worm"], desc: "Малоподвижная рыба-угорь холодных глубин. Может месяцами обходиться без еды." },
  { id: "crocodile_icefish", name: "Крокодиловая белокровка", latin: "Cryodraco antarcticus", loc: ["antarctic"], depth: [100, 800], rarity: "uncommon", time: "night", weight: [0.5, 2], price: 140, strength: 3, shape: "long", colors: { body: "#b8c4c8", belly: "#e0e8ec", fin: "#98a8b0", accent: "#e8f0f4" }, pattern: "none", bait: ["shrimp", "cutbait"], desc: "Прозрачная кровь и челюсти крокодила. Охотится на криль у кромки шельфового льда." },
  { id: "spiny_plunderfish", name: "Колючая харпагифера", latin: "Harpagifer antarcticus", loc: ["antarctic"], depth: [0, 60], rarity: "uncommon", time: "day", season: [1], weight: [0.01, 0.05], price: 1200, strength: 1, shape: "angler", colors: { body: "#8a5a3a", belly: "#c89a70", fin: "#5a3a24" }, pattern: "spots", bait: ["shrimp", "worm"], desc: "Крошечный рыбка-колючка приливных луж. Самец неделями охраняет кладку, не отходя ни на шаг." },
  { id: "blue_whiting_giant", name: "Южная путассу", latin: "Micromesistius australis", loc: ["antarctic"], depth: [50, 800], rarity: "rare", time: "any", season: [0, 1], weight: [0.5, 1.5], price: 180, strength: 3, shape: "fusiform", colors: { body: "#5a6a8a", belly: "#e8eef4", fin: "#4a5a7a" }, pattern: "gradient", bait: ["jig", "shrimp"], desc: "Южная родственница путассу, стаи которой подходят к шельфу только в полярное лето." },
  { id: "bathydraco", name: "Глубинный дракон", latin: "Bathydraco scotiae", loc: ["antarctic"], depth: [500, 1200], rarity: "epic", time: "night", weight: [0.3, 1], price: 1800, strength: 3, shape: "long", colors: { body: "#2a2a30", belly: "#4a4a54", fin: "#1a1a20", accent: "#8a9ab8" }, pattern: "none", glow: "#80c0ff", bait: ["glow", "cutbait"], desc: "Одна из самых глубоководных антарктических рыб. Обнаружена лишь в нескольких экземплярах и почти не изучена." },
];
