import type { FishDef } from "./types";

// Третий том кодекса: обитатели лимана, шхер, туманного берега, мангров, вулканических островов и ледяного шельфа
export const FISH_VOL3: FishDef[] = [
  // ───────────── ЛИМАН ─────────────
  { id: "taran", name: "Тарань", latin: "Rutilus heckelii", loc: ["estuary"], depth: [0, 6], rarity: "common", time: "any", weight: [0.1, 0.6], price: 60, strength: 2, shape: "fusiform", colors: { body: "#8a9aa0", belly: "#eef0ec", fin: "#c86a4a" }, pattern: "gradient", bait: ["worm"], desc: "Серебристая плотва солоноватых лиманов с красными плавниками. Весной идёт в реки таким плотным ходом, что вода рябит от спин." },
  { id: "pilengas", name: "Пиленгас", latin: "Planiliza haematocheila", loc: ["estuary"], depth: [0, 8], rarity: "uncommon", time: "day", weight: [0.5, 4], price: 40, strength: 4, shape: "fusiform", colors: { body: "#6a7a84", belly: "#e8ecee", fin: "#4a5a64", accent: "#c86a4a" }, pattern: "stripes", bait: ["worm", "shrimp"], desc: "Дальневосточная кефаль, прижившаяся в южных лиманах. Выносит и пресную воду, и рассол, а на крючке бьётся отчаянно." },
  { id: "sazan", name: "Сазан", latin: "Cyprinus carpio", loc: ["estuary"], depth: [1, 10], rarity: "uncommon", time: "twilight", weight: [1, 12], price: 30, strength: 6, shape: "deep", colors: { body: "#8a7a3a", belly: "#d8c890", fin: "#6a5a2a", accent: "#b08a3a" }, pattern: "none", bait: ["worm"], desc: "Дикий предок карпа в крупной золотой чешуе. Осторожен, берёт наживку медленно, а потом уходит в камыш так, что леска поёт." },
  { id: "zander", name: "Судак", latin: "Sander lucioperca", loc: ["estuary"], depth: [3, 12], rarity: "uncommon", time: "night", weight: [0.8, 6], price: 55, strength: 5, shape: "fusiform", colors: { body: "#7a8a70", belly: "#e6e8dc", fin: "#5a6a50", accent: "#2a3424" }, pattern: "bars", bait: ["livebait", "spoon"], desc: "Ночной хищник мутной воды. Большие глаза с отражающим слоем видят в темноте, а клыки не выпускают добычу." },
  { id: "shemaya", name: "Шемая", latin: "Alburnus chalcoides", loc: ["estuary"], depth: [0, 6], rarity: "rare", time: "day", season: [0], weight: [0.1, 0.5], price: 260, strength: 3, shape: "fusiform", colors: { body: "#6a8aa0", belly: "#f2f4f4", fin: "#8a9aa0" }, pattern: "gradient", bait: ["worm"], desc: "Изящная узкая рыбка с перламутровыми боками. Ходит в реки лишь весной; вяленую шемаю когда-то подавали к царскому столу." },
  { id: "catfish", name: "Сом", latin: "Silurus glanis", loc: ["estuary"], depth: [4, 12], rarity: "rare", time: "night", weight: [8, 80], price: 18, strength: 8, shape: "eel", colors: { body: "#3a3e30", belly: "#a8a890", fin: "#2a2e22" }, pattern: "spots", bait: ["livebait", "worm"], desc: "Хозяин омутов с широкой пастью и длинными усами. Днём лежит в ямах фарватера, ночью выходит на мелководье за лягушками и утятами." },
  { id: "beluga", name: "Белуга-царица", latin: "Huso huso", loc: ["estuary"], depth: [6, 12], rarity: "legendary", time: "night", season: [0, 2], weight: [300, 800], price: 25, strength: 10, shape: "long", colors: { body: "#8a9098", belly: "#e8eaec", fin: "#6a7078", accent: "#d0d4d8" }, pattern: "none", bait: ["livebait"], desc: "Древнейшая белуга лимана, которой, по словам рыбаков, больше ста лет. Поднимается из моря весной и осенью, ночью, и тянет лодку против течения." },

  // ───────────── ШХЕРЫ ─────────────
  { id: "perch", name: "Речной окунь", latin: "Perca fluviatilis", loc: ["skerries"], depth: [0, 10], rarity: "common", time: "day", weight: [0.1, 1], price: 70, strength: 2, shape: "deep", colors: { body: "#7a8a3a", belly: "#e8d8a0", fin: "#d85a2a", accent: "#2a3a1a" }, pattern: "bars", bait: ["worm", "shrimp"], desc: "Полосатый окунь, привыкший к солоноватой балтийской воде. Держится стайками у гранитных плит и жадно хватает всё, что движется." },
  { id: "smelt", name: "Корюшка", latin: "Osmerus eperlanus", loc: ["skerries"], depth: [0, 20], rarity: "common", time: "any", season: [0, 3], weight: [0.02, 0.12], price: 280, strength: 1, shape: "fusiform", colors: { body: "#8aa0a8", belly: "#f2f6f6", fin: "#9ab0b8" }, pattern: "stripes", bait: ["worm", "shrimp"], desc: "Полупрозрачная рыбка, свежая пахнет огурцом. Зимой и ранней весной подходит к островам такими стаями, что клюёт на каждом забросе." },
  { id: "pike", name: "Щука", latin: "Esox lucius", loc: ["skerries"], depth: [0, 8], rarity: "uncommon", time: "day", weight: [1, 10], price: 40, strength: 6, shape: "long", colors: { body: "#5a6a3a", belly: "#e0dcb0", fin: "#8a6a3a", accent: "#c8c880" }, pattern: "spots", bait: ["livebait", "spoon", "wobbler"], desc: "Засадный хищник тростниковых заливов. Стоит неподвижно, как бревно, и бросается на добычу быстрее, чем успеваешь моргнуть." },
  { id: "whitefish", name: "Сиг", latin: "Coregonus lavaretus", loc: ["skerries"], depth: [5, 30], rarity: "uncommon", time: "any", season: [2, 3], weight: [0.5, 3], price: 90, strength: 4, shape: "fusiform", colors: { body: "#7a8a98", belly: "#f0f2f4", fin: "#5a6a78" }, pattern: "gradient", bait: ["worm", "shrimp"], desc: "Серебристая северная рыба с маленьким ртом. Поздней осенью собирается в проливах перед нерестом, и тогда её ловят всем посёлком." },
  { id: "eel", name: "Угорь", latin: "Anguilla anguilla", loc: ["skerries"], depth: [5, 70], rarity: "rare", time: "night", weight: [0.5, 4], price: 180, strength: 6, shape: "eel", colors: { body: "#3a4a2a", belly: "#d8d0a0", fin: "#2a3a1a" }, pattern: "gradient", bait: ["worm", "livebait"], desc: "Рождается в Саргассовом море и через тысячи километров приплывает в холодные шхеры. Живёт здесь десятилетиями, а потом уходит обратно умирать." },
  { id: "atl_sturgeon", name: "Балтийский осётр", latin: "Acipenser oxyrinchus", loc: ["skerries"], depth: [20, 70], rarity: "epic", time: "twilight", weight: [30, 150], price: 25, strength: 9, shape: "long", colors: { body: "#5a5e54", belly: "#d8d6c8", fin: "#3a3e36", accent: "#c8c4b0" }, pattern: "spots", bait: ["worm", "shrimp"], desc: "Когда-то его считали исчезнувшим из Балтики. Теперь в глубоких ложбинах снова видят этих рыб с рядами костяных щитков." },
  { id: "pike_legend", name: "Щука с острова Ульвё", latin: "Esox lucius ulvoensis", loc: ["skerries"], depth: [2, 12], rarity: "legendary", time: "twilight", weather: ["fog"], weight: [18, 30], price: 60, strength: 9, shape: "long", colors: { body: "#4a5a2e", belly: "#d8d4a0", fin: "#7a5a2a", accent: "#e0e0a0" }, pattern: "spots", bait: ["livebait"], desc: "Щука длиной в человеческий рост, о которой в шхерах рассказывают полвека. Выходит из тростника только в туманные сумерки." },

  // ───────────── ТУМАННЫЙ БЕРЕГ ─────────────
  { id: "surfperch", name: "Полосатая живородка", latin: "Embiotoca lateralis", loc: ["kelp"], depth: [0, 20], rarity: "common", time: "any", weight: [0.2, 1], price: 90, strength: 2, shape: "deep", colors: { body: "#c07a4a", belly: "#e8c8a0", fin: "#8a5a3a", accent: "#4a80c0" }, pattern: "stripes", bait: ["shrimp", "worm"], desc: "Медно-рыжая рыба с синими полосками на морде. Не мечет икру: мальки рождаются живыми и сразу умеют плавать." },
  { id: "garibaldi", name: "Гарибальди", latin: "Hypsypops rubicundus", loc: ["kelp"], depth: [0, 14], rarity: "common", time: "day", weight: [0.2, 0.8], price: 200, strength: 2, shape: "deep", colors: { body: "#ff7a1a", belly: "#ffa040", fin: "#f06a10" }, pattern: "none", bait: ["shrimp"], desc: "Ярко-оранжевая рыба-ласточка, видная в зелёной воде за десять метров. Самец чистит «сад» из красных водорослей и защищает его от любого пришельца." },
  { id: "kelp_bass", name: "Калико-окунь", latin: "Paralabrax clathratus", loc: ["kelp"], depth: [2, 32], rarity: "common", time: "any", weight: [0.5, 3.5], price: 50, strength: 4, shape: "fusiform", colors: { body: "#5a5a3a", belly: "#c8c0a0", fin: "#4a4a2e", accent: "#d8d0b0" }, pattern: "spots", bait: ["livebait", "shrimp"], desc: "Пятнистый окунь водорослевого леса. Висит между стеблями ламинарии и бросается на всё, что проплывает мимо." },
  { id: "sheephead", name: "Калифорнийский губан", latin: "Semicossyphus pulcher", loc: ["kelp"], depth: [3, 30], rarity: "uncommon", time: "day", weight: [1, 12], price: 35, strength: 5, shape: "deep", colors: { body: "#2a2a2a", belly: "#e8e0d8", fin: "#1a1a1a", accent: "#d0503a" }, pattern: "none", bait: ["shrimp"], desc: "Самцы чёрные с красной «жилеткой» посередине тела. Крепкими зубами крошат морских ежей и так спасают водорослевый лес от гибели." },
  { id: "lingcod", name: "Зубатый терпуг", latin: "Ophiodon elongatus", loc: ["kelp"], depth: [8, 140], rarity: "uncommon", time: "any", weight: [2, 25], price: 35, strength: 7, shape: "long", colors: { body: "#5a6a50", belly: "#c8ccb0", fin: "#3a4a34" }, pattern: "spots", bait: ["livebait", "squid"], desc: "Большая голова и восемнадцать клыков. Мясо у некоторых особей голубовато-зелёное; после варки оно белеет." },
  { id: "white_seabass", name: "Белый горбыль", latin: "Atractoscion nobilis", loc: ["kelp"], depth: [5, 32], rarity: "rare", time: "twilight", weather: ["fog", "cloudy"], weight: [5, 35], price: 40, strength: 7, shape: "fusiform", colors: { body: "#8a98a4", belly: "#eef0f2", fin: "#6a7884" }, pattern: "gradient", bait: ["squid", "livebait"], desc: "Серебряный призрак водорослевого леса. Приходит с туманом за стаями кальмаров, и рыбаки ждут его годами." },
  { id: "leopard_shark", name: "Леопардовая акула", latin: "Triakis semifasciata", loc: ["kelp"], depth: [1, 30], rarity: "rare", time: "day", weight: [5, 18], price: 25, strength: 6, shape: "shark", colors: { body: "#8a8070", belly: "#e8e4d8", fin: "#6a6050", accent: "#2a2620" }, pattern: "bars", bait: ["squid", "shrimp"], desc: "Безобидная акула с тёмными седловидными пятнами. Летом собирается сотнями на прогретом мелководье бухт." },
  { id: "giant_seabass", name: "Гигантский морской окунь", latin: "Stereolepis gigas", loc: ["kelp"], depth: [8, 50], rarity: "epic", time: "any", weight: [60, 250], price: 12, strength: 9, shape: "deep", colors: { body: "#3a3a3a", belly: "#8a8a8a", fin: "#2a2a2a" }, pattern: "spots", bait: ["livebait", "squid"], desc: "Окунь размером с небольшой автомобиль, живёт до ста лет. Узор пятен у каждой особи свой, как отпечаток пальца." },
  { id: "octopus", name: "Гигантский осьминог", latin: "Enteroctopus dofleini", loc: ["kelp"], depth: [15, 140], rarity: "epic", time: "night", weight: [15, 70], price: 20, strength: 8, shape: "squid", colors: { body: "#b04a3a", belly: "#e08a70", fin: "#8a3a2a" }, pattern: "spots", bait: ["shrimp", "squid"], desc: "Крупнейший осьминог мира. Открывает банки, узнаёт людей в лицо и выбирается из любой ловушки." },

  // ───────────── МАНГРОВЫЕ ПРОТОКИ ─────────────
  { id: "mudskipper", name: "Илистый прыгун", latin: "Periophthalmus barbarus", loc: ["mangrove"], depth: [0, 2], rarity: "common", time: "day", weight: [0.01, 0.05], price: 600, strength: 1, shape: "fusiform", colors: { body: "#6a6a4a", belly: "#b8b090", fin: "#4a8ab0", accent: "#80c0e0" }, pattern: "spots", bait: ["worm"], desc: "Рыба, которая ходит по илу на грудных плавниках и дышит кожей. Выпученные глаза умеют моргать — единственные среди рыб." },
  { id: "mangrove_snapper", name: "Мангровый луциан", latin: "Lutjanus griseus", loc: ["mangrove"], depth: [1, 16], rarity: "common", time: "any", weight: [0.3, 3], price: 70, strength: 4, shape: "deep", colors: { body: "#7a5a4a", belly: "#d8b8a0", fin: "#a0503a" }, pattern: "none", bait: ["shrimp", "livebait"], desc: "Серо-бурый луциан, прячущийся между корнями. Хитёр: долго рассматривает наживку и чаще уходит, чем берёт." },
  { id: "archerfish", name: "Брызгун", latin: "Toxotes jaculatrix", loc: ["mangrove"], depth: [0, 5], rarity: "uncommon", time: "day", weight: [0.05, 0.3], price: 350, strength: 2, shape: "deep", colors: { body: "#c8c8b0", belly: "#f0f0e0", fin: "#e0c040", accent: "#1a1a1a" }, pattern: "spots", bait: ["shrimp", "worm"], desc: "Сбивает насекомых с листьев метким плевком на два метра и учитывает преломление света на поверхности воды." },
  { id: "snook", name: "Снук", latin: "Centropomus undecimalis", loc: ["mangrove"], depth: [0, 14], rarity: "uncommon", time: "twilight", weight: [1, 12], price: 45, strength: 6, shape: "fusiform", colors: { body: "#a8a48a", belly: "#eeeade", fin: "#c8b050", accent: "#1a1a1a" }, pattern: "stripes", bait: ["livebait", "wobbler"], desc: "Хищник с чёрной линией вдоль бока. Засекает добычу у кромки корней, а на крючке уводит леску в самые заросли." },
  { id: "jack_crevalle", name: "Каранкс-кревалле", latin: "Caranx hippos", loc: ["mangrove"], depth: [0, 16], rarity: "uncommon", time: "day", weight: [1, 15], price: 25, strength: 7, shape: "deep", colors: { body: "#5a6a6a", belly: "#e0d890", fin: "#e0c040" }, pattern: "gradient", bait: ["livebait", "spoon"], desc: "Стайный задира тёплых вод, который не сдаётся до конца. После вываживания и рыбак, и рыба одинаково без сил." },
  { id: "tarpon", name: "Тарпон", latin: "Megalops atlanticus", loc: ["mangrove"], depth: [2, 16], rarity: "rare", time: "any", weight: [15, 90], price: 12, strength: 9, shape: "fusiform", colors: { body: "#8a9aa8", belly: "#f0f4f6", fin: "#6a7a88", accent: "#d8dce0" }, pattern: "none", bait: ["livebait", "wobbler"], desc: "«Серебряный король»: чешуя размером с ладонь, прыжки на три метра. Может глотать воздух с поверхности и потому живёт даже в бедных кислородом протоках." },
  { id: "lemon_shark", name: "Лимонная акула", latin: "Negaprion brevirostris", loc: ["mangrove"], depth: [0, 16], rarity: "rare", time: "night", weight: [20, 90], price: 12, strength: 8, shape: "shark", colors: { body: "#c8b870", belly: "#f0ead0", fin: "#a89850" }, pattern: "gradient", bait: ["livebait", "squid"], desc: "Желтоватая акула, выросшая в мангровых «яслях». Взрослые самки возвращаются рожать туда же, где родились сами." },
  { id: "goliath", name: "Групер-голиаф", latin: "Epinephelus itajara", loc: ["mangrove"], depth: [3, 16], rarity: "epic", time: "any", weight: [80, 300], price: 8, strength: 10, shape: "deep", colors: { body: "#6a6040", belly: "#b0a880", fin: "#4a4028" }, pattern: "spots", bait: ["livebait"], desc: "Групер весом с медведя. Молодь растёт среди корней мангров, а взрослый издаёт гул, который чувствуешь всем телом." },
  { id: "sawfish", name: "Старая пила-рыба", latin: "Pristis pectinata", loc: ["mangrove"], depth: [6, 16], rarity: "legendary", time: "night", weather: ["rain", "storm"], weight: [200, 350], price: 10, strength: 10, shape: "shark", colors: { body: "#6a6a58", belly: "#e8e6dc", fin: "#4a4a3c" }, pattern: "none", bait: ["livebait"], desc: "Скат с зубчатым рылом длиной в два метра. Этим «ножом» он глушит рыбу, как саблей. Выходит из протоки только в ливень." },

  // ───────────── ВУЛКАНИЧЕСКИЙ АРХИПЕЛАГ ─────────────
  { id: "soldierfish", name: "Рыба-солдат", latin: "Myripristis berndti", loc: ["volcano"], depth: [1, 30], rarity: "common", time: "night", weight: [0.1, 0.5], price: 180, strength: 2, shape: "deep", colors: { body: "#e04a3a", belly: "#f0a090", fin: "#f0f0e0" }, pattern: "none", bait: ["shrimp"], desc: "Алая ночная рыба с огромными глазами. Днём стоит стаей в лавовых пещерах, ночью выходит кормиться планктоном." },
  { id: "convict_tang", name: "Полосатый хирург", latin: "Acanthurus triostegus", loc: ["volcano"], depth: [0, 20], rarity: "common", time: "day", weight: [0.1, 0.4], price: 160, strength: 2, shape: "deep", colors: { body: "#d8dcd0", belly: "#f0f2ea", fin: "#c8ccc0", accent: "#1a1a1a" }, pattern: "bars", bait: ["shrimp"], desc: "Шесть чёрных полос на светлом теле, как на тюремной робе. Огромными стаями объедает водоросли с молодой лавы." },
  { id: "bluefin_trevally", name: "Синеперый каранкс", latin: "Caranx melampygus", loc: ["volcano"], depth: [0, 30], rarity: "uncommon", time: "day", weight: [2, 12], price: 30, strength: 6, shape: "deep", colors: { body: "#5a7080", belly: "#d8e0e4", fin: "#2a70d0", accent: "#40a0f0" }, pattern: "spots", bait: ["livebait", "spoon"], desc: "Хищник с электрически-синими плавниками. Охотится вместе с муренами: одна выгоняет рыбу из щелей, другой хватает её снаружи." },
  { id: "opakapaka", name: "Розовый луциан", latin: "Pristipomoides filamentosus", loc: ["volcano"], depth: [40, 300], rarity: "uncommon", time: "any", weight: [1, 8], price: 50, strength: 5, shape: "fusiform", colors: { body: "#d88a9a", belly: "#f4d8dc", fin: "#a8b8e0" }, pattern: "gradient", bait: ["squid", "shrimp"], desc: "Нежно-розовый луциан глубоких склонов. На островах его подают на праздники как лучшую рыбу года." },
  { id: "amberjack", name: "Большая сериола", latin: "Seriola dumerili", loc: ["volcano"], depth: [10, 90], rarity: "uncommon", time: "day", weight: [8, 60], price: 20, strength: 8, shape: "fusiform", colors: { body: "#5a6a7a", belly: "#e8e4d0", fin: "#d0b040", accent: "#e0c040" }, pattern: "stripes", bait: ["livebait", "wobbler"], desc: "Янтарная полоса через глаз и сила, от которой ноют плечи. Рыбаки прозвали её «ослом рифа» за упрямство на вываживании." },
  { id: "onaga", name: "Онага", latin: "Etelis coruscans", loc: ["volcano"], depth: [150, 500], rarity: "rare", time: "any", weight: [2, 15], price: 60, strength: 6, shape: "fusiform", colors: { body: "#e03a3a", belly: "#f4b0b0", fin: "#c02a2a" }, pattern: "none", bait: ["squid"], desc: "Длиннохвостый красный луциан сумеречных глубин. На островах его дарят на свадьбы: красный цвет приносит удачу." },
  { id: "galapagos_shark", name: "Галапагосская акула", latin: "Carcharhinus galapagensis", loc: ["volcano"], depth: [10, 90], rarity: "rare", time: "any", weight: [40, 150], price: 8, strength: 9, shape: "shark", colors: { body: "#6a7078", belly: "#e6e8ea", fin: "#50585e" }, pattern: "gradient", bait: ["livebait", "squid"], desc: "Акула океанических островов. Кружит у подножия лавовых склонов и первой приходит на запах крови." },
  { id: "black_marlin", name: "Чёрный марлин", latin: "Istiompax indica", loc: ["volcano"], depth: [0, 200], rarity: "epic", time: "day", weight: [150, 600], price: 9, strength: 10, shape: "billfish", colors: { body: "#1a2230", belly: "#c8ccd4", fin: "#10141c", accent: "#6a7a90" }, pattern: "gradient", bait: ["livebait"], desc: "Грудные плавники не складываются — они застыли, как крылья. Самый быстрый и тяжёлый из марлинов, трофей всей жизни." },

  // ───────────── ЛЕДЯНОЙ ШЕЛЬФ ─────────────
  { id: "silverfish", name: "Антарктическая серебрянка", latin: "Pleuragramma antarcticum", loc: ["antarctic"], depth: [0, 220], rarity: "common", time: "any", weight: [0.02, 0.1], price: 400, strength: 1, shape: "fusiform", colors: { body: "#b8c4c8", belly: "#f4f8f8", fin: "#98a4a8" }, pattern: "gradient", bait: ["shrimp"], desc: "Главная рыба Южного океана: ею кормятся пингвины, тюлени и киты. Икру вымётывает прямо под морским льдом." },
  { id: "marbled_rockcod", name: "Мраморная нототения", latin: "Notothenia rossii", loc: ["antarctic"], depth: [10, 220], rarity: "common", time: "any", weight: [0.5, 5], price: 60, strength: 4, shape: "fusiform", colors: { body: "#6a5a4a", belly: "#c8b8a0", fin: "#4a3a2a" }, pattern: "spots", bait: ["worm", "shrimp"], desc: "Пятнистая донная рыба ледяных вод. Белки-антифризы в крови не дают ей замёрзнуть при минус двух." },
  { id: "bald_notothen", name: "Лысая нототения", latin: "Pagothenia borchgrevinki", loc: ["antarctic"], depth: [0, 60], rarity: "common", time: "any", weight: [0.1, 0.5], price: 180, strength: 2, shape: "fusiform", colors: { body: "#a8a898", belly: "#e8e8e0", fin: "#88887a" }, pattern: "spots", bait: ["shrimp", "worm"], desc: "Живёт прямо в ледяной крошке под паковым льдом и прячется между кристаллами. Кровь у неё замерзает лишь при минус двух с лишним." },
  { id: "macrourus", name: "Антарктический макрурус", latin: "Macrourus whitsoni", loc: ["antarctic"], depth: [300, 1200], rarity: "uncommon", time: "any", weight: [1, 5], price: 70, strength: 3, shape: "long", colors: { body: "#6a6a70", belly: "#9a9aa0", fin: "#4a4a50" }, pattern: "none", bait: ["squid", "shrimp"], desc: "Долгохвост ледяных глубин с огромными глазами и крысиным хвостом. Главная добыча клыкача и полярных акул." },
  { id: "icefish", name: "Ледяная рыба", latin: "Chaenocephalus aceratus", loc: ["antarctic"], depth: [50, 480], rarity: "uncommon", time: "any", weight: [0.5, 3], price: 120, strength: 3, shape: "long", colors: { body: "#c8d0d4", belly: "#e8eef0", fin: "#a8b4b8", accent: "#e0e8ec" }, pattern: "none", bait: ["shrimp"], desc: "Единственное позвоночное без гемоглобина: кровь прозрачная, как вода. Сердце у неё огромное, а кислород растворяется прямо в плазме." },
  { id: "antarctic_skate", name: "Антарктический скат", latin: "Bathyraja maccaini", loc: ["antarctic"], depth: [80, 480], rarity: "uncommon", time: "any", weight: [3, 15], price: 30, strength: 5, shape: "ray", colors: { body: "#5a5048", belly: "#e8e0d8", fin: "#3a302a" }, pattern: "spots", bait: ["squid", "shrimp"], desc: "Медлительный скат ледяных глубин. Откладывает яйца в кожистых капсулах, и детёныши развиваются в них несколько лет." },
  { id: "dragonfish", name: "Антарктический дракон", latin: "Gymnodraco acuticeps", loc: ["antarctic"], depth: [20, 480], rarity: "rare", time: "night", weight: [0.2, 1], price: 400, strength: 3, shape: "long", colors: { body: "#8a7a5a", belly: "#d8d0b8", fin: "#5a4a30", accent: "#c89040" }, pattern: "bars", bait: ["shrimp"], desc: "Вытянутая рыба с «крокодильей» мордой и без чешуи. Самцы охраняют кладку под льдом дольше года." },
  { id: "toothfish", name: "Антарктический клыкач", latin: "Dissostichus mawsoni", loc: ["antarctic"], depth: [200, 1200], rarity: "rare", time: "any", weight: [20, 120], price: 25, strength: 8, shape: "fusiform", colors: { body: "#4a4e52", belly: "#9aa0a4", fin: "#34383c" }, pattern: "none", bait: ["squid"], desc: "Главный хищник подо льдом, живёт полвека. Плавательного пузыря нет: плавучесть дают жир и лёгкие кости." },
  { id: "sleeper_shark", name: "Южная полярная акула", latin: "Somniosus antarcticus", loc: ["antarctic"], depth: [300, 1200], rarity: "epic", time: "night", weight: [200, 600], price: 5, strength: 10, shape: "shark", colors: { body: "#3a3c3e", belly: "#6a6c6e", fin: "#2a2c2e" }, pattern: "spots", bait: ["squid"], desc: "Медленная, как сон, и тяжёлая, как якорь. В её желудках находили клювы колоссальных кальмаров." },
  { id: "colossal_squid", name: "Колоссальный кальмар", latin: "Mesonychoteuthis hamiltoni", loc: ["antarctic"], depth: [700, 1200], rarity: "legendary", time: "night", weather: ["snow", "fog"], weight: [400, 700], price: 12, strength: 10, shape: "squid", colors: { body: "#b04030", belly: "#e08070", fin: "#802a20" }, pattern: "spots", bait: ["squid", "glow"], desc: "Самые большие глаза в животном мире, крючья на щупальцах вместо присосок. Живым его видели считанные разы, и всегда подо льдом в метель." },
];
