import { FISH_EXTRA } from "./fish2";
import { FISH_VOL3 } from "./fish3";
import { FISH_VOL4 } from "./fish4";
import { FISH_VOL5 } from "./fish5";
import { ensureDistinct } from "./distinct";
import type { FishDef } from "./types";

// Первый том кодекса. Каждый вид — свои глубины, время, погода, сезон, наживка.
const FISH_BASE: FishDef[] = [
  // ───────────── ТИХАЯ БУХТА (0–18 м) ─────────────
  { id: "goby", name: "Бычок-кругляк", latin: "Neogobius melanostomus", loc: ["bay", "estuary"], depth: [0, 10], rarity: "common", time: "any", weight: [0.05, 0.4], price: 38, strength: 1, shape: "fusiform", colors: { body: "#7a6a4a", belly: "#c9b98a", fin: "#5a4a30" }, pattern: "spots", bait: ["worm"], desc: "Большеголовый хозяин камней. Клюёт на всё и всегда — первый друг любого рыбака." },
  { id: "horse_mackerel", name: "Ставрида", latin: "Trachurus mediterraneus", loc: ["bay", "cape"], depth: [2, 14], rarity: "common", time: "day", weight: [0.1, 0.6], price: 42, strength: 2, shape: "fusiform", colors: { body: "#6f8fa8", belly: "#e6eef2", fin: "#c9b24a" }, pattern: "gradient", bait: ["shrimp", "spoon"], desc: "Ходит стаями у поверхности. Боковая линия покрыта костяными щитками." },
  { id: "mullet", name: "Кефаль-лобан", latin: "Mugil cephalus", loc: ["bay", "estuary"], depth: [0, 6], rarity: "common", time: "day", weight: [0.3, 2.2], price: 34, strength: 3, shape: "fusiform", colors: { body: "#8397a3", belly: "#e8ecee", fin: "#6b7a84" }, pattern: "stripes", bait: ["worm", "shrimp"], desc: "Осторожная и сильная. Выпрыгивает из воды, если что-то её напугало." },
  { id: "scorpionfish", name: "Морской ёрш", latin: "Scorpaena porcus", loc: ["bay"], depth: [5, 18], rarity: "uncommon", time: "night", weight: [0.1, 0.7], price: 70, strength: 2, shape: "deep", colors: { body: "#9a4a32", belly: "#d69a70", fin: "#6e2e1c" }, pattern: "spots", bait: ["shrimp", "livebait"], desc: "Ядовитые шипы и маскировка под камень. Ночью выходит на охоту." },
  { id: "turbot", name: "Калкан", latin: "Scophthalmus maeoticus", loc: ["bay"], depth: [8, 18], rarity: "uncommon", time: "any", season: [0, 2], weight: [0.8, 6], price: 55, strength: 4, shape: "flat", colors: { body: "#6e6448", belly: "#e8e2cc", fin: "#4e4632" }, pattern: "spots", bait: ["livebait"], desc: "Камбала с костяными бугорками. Весной и осенью подходит к берегу." },
  { id: "croaker", name: "Горбыль", latin: "Sciaena umbra", loc: ["bay"], depth: [3, 14], rarity: "uncommon", time: "twilight", weight: [0.3, 2.5], price: 60, strength: 3, shape: "deep", colors: { body: "#5b4a3a", belly: "#b8a07a", fin: "#2e241a" }, pattern: "none", bait: ["worm", "shrimp"], desc: "Издаёт урчащие звуки плавательным пузырём. Любит сумерки." },
  { id: "red_mullet", name: "Барабуля", latin: "Mullus barbatus", loc: ["bay"], depth: [5, 16], rarity: "common", time: "day", season: [1, 2], weight: [0.05, 0.3], price: 90, strength: 1, shape: "fusiform", colors: { body: "#d8665a", belly: "#f4d0c0", fin: "#e8a040" }, pattern: "gradient", bait: ["worm"], desc: "Роется в песке усиками. Нежное мясо — деликатес со времён Рима." },
  { id: "wrasse", name: "Зеленушка", latin: "Symphodus tinca", loc: ["bay"], depth: [1, 9], rarity: "common", time: "day", weight: [0.05, 0.35], price: 40, strength: 1, shape: "fusiform", colors: { body: "#4a8a5a", belly: "#c8e0a8", fin: "#2e6a8a", accent: "#e0a040" }, pattern: "spots", bait: ["worm", "shrimp"], desc: "Пёстрая рыбка водорослевых зарослей. Меняет пол в течение жизни." },
  { id: "garfish", name: "Сарган", latin: "Belone belone", loc: ["bay", "cape"], depth: [0, 5], rarity: "uncommon", time: "twilight", weight: [0.1, 1], price: 65, strength: 3, shape: "long", colors: { body: "#3a6a8a", belly: "#dfeaf0", fin: "#2a4a60" }, pattern: "gradient", bait: ["spoon"], desc: "Рыба-игла с зелёными костями. Прыгает по волнам на рассвете." },
  { id: "salema", name: "Сарпа", latin: "Sarpa salpa", loc: ["bay"], depth: [2, 12], rarity: "rare", time: "day", weather: ["clear"], weight: [0.3, 1.8], price: 120, strength: 3, shape: "deep", colors: { body: "#9aa4a8", belly: "#e8eaea", fin: "#c9a830" }, pattern: "stripes", bait: ["worm"], desc: "Золотые полосы на серебре. Говорят, её мясо дарит странные сны." },
  { id: "bay_master", name: "Хозяин бухты", latin: "Mugil rex", loc: ["bay"], depth: [4, 18], rarity: "legendary", time: "twilight", weather: ["rain", "fog"], weight: [8, 14], price: 260, strength: 6, shape: "fusiform", colors: { body: "#50606a", belly: "#c8d0d4", fin: "#2e3a42", accent: "#d8c070" }, pattern: "stripes", bait: ["livebait"], desc: "Лобан-исполин со шрамом через всю спину. Старики видели его только в дождливые сумерки." },

  // ───────────── СКАЛИСТЫЙ МЫС (0–45 м) ─────────────
  { id: "sea_bass", name: "Морской окунь", latin: "Sebastes norvegicus", loc: ["cape", "fjord"], depth: [10, 45], rarity: "common", time: "any", weight: [0.5, 3.5], price: 48, strength: 4, shape: "deep", colors: { body: "#c8402a", belly: "#f0a080", fin: "#a02818" }, pattern: "none", bait: ["shrimp", "livebait"], desc: "Живородящий алый окунь скал. Может прожить больше ста лет." },
  { id: "cod", name: "Треска", latin: "Gadus morhua", loc: ["cape", "fjord", "skerries"], depth: [15, 45], rarity: "common", time: "any", season: [0, 2, 3], weight: [1, 12], price: 32, strength: 5, shape: "fusiform", colors: { body: "#8a7a50", belly: "#e8e0c8", fin: "#6a5a38" }, pattern: "spots", bait: ["worm", "livebait"], desc: "Рыба, построившая империи. Усик на подбородке ищет еду во тьме." },
  { id: "pollock", name: "Сайда", latin: "Pollachius virens", loc: ["skerries", "cape", "kelp"], depth: [5, 30], rarity: "common", time: "day", weight: [0.8, 6], price: 30, strength: 4, shape: "fusiform", colors: { body: "#3e5a4e", belly: "#c8d0cc", fin: "#2a3e34" }, pattern: "gradient", bait: ["spoon", "wobbler"], desc: "Тёмно-зелёная торпеда. Бьёт по блесне с разгона." },
  { id: "wolffish", name: "Зубатка полосатая", latin: "Anarhichas lupus", loc: ["kelp", "cape"], depth: [20, 45], rarity: "uncommon", time: "night", weight: [2, 12], price: 58, strength: 6, shape: "eel", colors: { body: "#6a7078", belly: "#b8bcc0", fin: "#4a5058" }, pattern: "bars", bait: ["shrimp", "squid"], desc: "Клыки, способные раскусить ракушку. Выглядит свирепо, на вкус — нежнейшая." },
  { id: "rockling", name: "Морской налим", latin: "Gaidropsarus vulgaris", loc: ["cape"], depth: [10, 35], rarity: "uncommon", time: "night", season: [2, 3], weight: [0.3, 1.8], price: 66, strength: 3, shape: "eel", colors: { body: "#8a6448", belly: "#dcc0a0", fin: "#5a3e2a" }, pattern: "spots", bait: ["worm"], desc: "Три усика и пятнистая шкура. Холодная вода делает его смелее." },
  { id: "ballan", name: "Губан-баллан", latin: "Labrus bergylta", loc: ["kelp", "cape"], depth: [3, 20], rarity: "common", time: "day", weight: [0.4, 3], price: 36, strength: 4, shape: "deep", colors: { body: "#5a7a4a", belly: "#d0c890", fin: "#3a5a3a", accent: "#e07040" }, pattern: "spots", bait: ["shrimp"], desc: "Толстые губы и пятнистые бока. Живёт в одной расщелине годами." },
  { id: "whiting", name: "Мерланг", latin: "Merlangius merlangus", loc: ["skerries", "cape"], depth: [10, 40], rarity: "common", time: "twilight", weight: [0.2, 1.5], price: 34, strength: 2, shape: "fusiform", colors: { body: "#b0a890", belly: "#f0ece0", fin: "#8a8270" }, pattern: "none", bait: ["worm", "shrimp"], desc: "Серебристый родственник трески. Сумерки — его время." },
  { id: "monkfish", name: "Морской чёрт", latin: "Lophius piscatorius", loc: ["cape"], depth: [30, 45], rarity: "rare", time: "any", weather: ["cloudy", "fog", "rain"], weight: [4, 25], price: 70, strength: 6, shape: "angler", colors: { body: "#6a5a44", belly: "#c8b898", fin: "#4a3e2e" }, pattern: "spots", bait: ["livebait"], desc: "Пасть на полтела и удочка на голове. Лежит на дне, словно коряга." },
  { id: "conger", name: "Морской угорь-конгер", latin: "Conger conger", loc: ["cape"], depth: [10, 45], rarity: "rare", time: "night", weight: [3, 30], price: 50, strength: 8, shape: "eel", colors: { body: "#4a4e58", belly: "#a8acb4", fin: "#2a2e38" }, pattern: "gradient", bait: ["squid", "livebait"], desc: "Хвостом цепляется за камни — вытащить его можно только упорством." },
  { id: "mackerel", name: "Скумбрия", latin: "Scomber scombrus", loc: ["cape", "ocean"], depth: [0, 20], rarity: "common", time: "day", season: [1, 2], weight: [0.2, 1], price: 44, strength: 3, shape: "fusiform", colors: { body: "#2a6a7a", belly: "#e8f0f0", fin: "#1a4a5a" }, pattern: "bars", bait: ["spoon", "shrimp"], desc: "Тигровые полосы и бешеный темперамент. Летом вода кипит от стай." },
  { id: "stone_patriarch", name: "Каменный патриарх", latin: "Sebastes antiquus", loc: ["cape"], depth: [35, 45], rarity: "legendary", time: "any", weather: ["storm"], weight: [15, 28], price: 240, strength: 8, shape: "deep", colors: { body: "#7a2a1a", belly: "#c87850", fin: "#4a1a10", accent: "#e8d0a0" }, pattern: "spots", bait: ["squid"], desc: "Окунь размером с ребёнка, обросший ракушками. Поднимается со дна только в шторм." },

  // ───────────── СЕВЕРНЫЙ ФЬОРД (0–160 м) ─────────────
  { id: "herring", name: "Сельдь", latin: "Clupea harengus", loc: ["skerries", "fjord"], depth: [0, 60], rarity: "common", time: "any", weight: [0.1, 0.5], price: 40, strength: 1, shape: "fusiform", colors: { body: "#4a6a8a", belly: "#f0f4f8", fin: "#3a5a7a" }, pattern: "gradient", bait: ["shrimp", "spoon"], desc: "Серебро северных морей. Стаи в миллионы рыб видны из космоса." },
  { id: "haddock", name: "Пикша", latin: "Melanogrammus aeglefinus", loc: ["fjord"], depth: [30, 130], rarity: "common", time: "any", weight: [0.5, 4], price: 42, strength: 4, shape: "fusiform", colors: { body: "#6a6a70", belly: "#e0e0e4", fin: "#3a3a40" }, pattern: "none", bait: ["worm", "shrimp"], desc: "Чёрное пятно на боку — «отпечаток пальца святого Петра»." },
  { id: "halibut", name: "Палтус", latin: "Hippoglossus hippoglossus", loc: ["fjord"], depth: [60, 160], rarity: "rare", time: "any", weight: [10, 80], price: 38, strength: 9, shape: "flat", colors: { body: "#4a4a3a", belly: "#f0f0e8", fin: "#2e2e22" }, pattern: "spots", bait: ["livebait", "squid"], desc: "Камбала-гигант. Рыбаки стреляют в крупных, прежде чем поднять на борт." },
  { id: "sea_trout", name: "Кумжа", latin: "Salmo trutta trutta", loc: ["skerries", "fjord"], depth: [0, 30], rarity: "uncommon", time: "twilight", weight: [0.8, 6], price: 80, strength: 5, shape: "fusiform", colors: { body: "#8a8a7a", belly: "#f0ece0", fin: "#5a5a4a" }, pattern: "spots", bait: ["wobbler", "spoon"], desc: "Морская форель, что возвращается в реку, где родилась." },
  { id: "salmon", name: "Атлантический лосось", latin: "Salmo salar", loc: ["fjord", "skerries"], depth: [0, 40], rarity: "rare", time: "any", season: [2], weight: [3, 18], price: 95, strength: 7, shape: "fusiform", colors: { body: "#7a8a9a", belly: "#f4ecec", fin: "#4a5a6a", accent: "#d88070" }, pattern: "spots", bait: ["wobbler", "spoon"], desc: "Король фьордов. Осенью идёт на нерест против течения и водопадов." },
  { id: "plaice", name: "Полярная камбала", latin: "Liopsetta glacialis", loc: ["fjord"], depth: [40, 120], rarity: "common", time: "any", season: [3, 0], weight: [0.3, 2], price: 46, strength: 2, shape: "flat", colors: { body: "#5a5040", belly: "#f0e8d8", fin: "#3a3428", accent: "#d86030" }, pattern: "spots", bait: ["worm"], desc: "Не замерзает благодаря белкам-антифризам в крови." },
  { id: "capelin", name: "Мойва", latin: "Mallotus villosus", loc: ["fjord"], depth: [0, 40], rarity: "common", time: "any", season: [3], weight: [0.02, 0.06], price: 300, strength: 1, shape: "fusiform", colors: { body: "#5a8a7a", belly: "#f0f4f0", fin: "#3a6a5a" }, pattern: "gradient", bait: ["shrimp"], desc: "Крошечная, но без неё рухнула бы вся северная пищевая цепь." },
  { id: "spotted_wolffish", name: "Пятнистая зубатка", latin: "Anarhichas minor", loc: ["fjord"], depth: [80, 160], rarity: "uncommon", time: "night", weight: [3, 20], price: 52, strength: 7, shape: "eel", colors: { body: "#5a5a50", belly: "#b8b8a8", fin: "#3a3a30" }, pattern: "spots", bait: ["squid", "shrimp"], desc: "Пятнистый страж глубоких фьордов. Челюсти крушат морских ежей." },
  { id: "chimaera", name: "Европейская химера", latin: "Chimaera monstrosa", loc: ["kelp", "fjord"], depth: [110, 160], rarity: "rare", time: "night", weight: [0.8, 2.5], price: 140, strength: 4, shape: "long", colors: { body: "#9a8a7a", belly: "#d8d0c8", fin: "#6a5a4a", accent: "#8ab0c8" }, pattern: "gradient", bait: ["shrimp"], desc: "«Морская крыса» — хрящевой призрак с глазами, отражающими свет." },
  { id: "char", name: "Арктический голец", latin: "Salvelinus alpinus", loc: ["fjord"], depth: [0, 30], rarity: "uncommon", time: "day", weather: ["cloudy", "snow"], weight: [0.5, 5], price: 90, strength: 5, shape: "fusiform", colors: { body: "#3a5a5a", belly: "#e87848", fin: "#c85030" }, pattern: "spots", bait: ["wobbler", "worm"], desc: "Самая северная пресноводная рыба, зимующая в солёных фьордах." },
  { id: "nordvik_halibut", name: "Белый палтус Нордвика", latin: "Hippoglossus albus", loc: ["fjord"], depth: [120, 160], rarity: "legendary", time: "any", weather: ["snow"], season: [3], weight: [90, 180], price: 60, strength: 10, shape: "flat", colors: { body: "#e8ecec", belly: "#ffffff", fin: "#c0c8cc", accent: "#90a8b8" }, pattern: "none", bait: ["livebait", "squid"], desc: "Белоснежная тень подо льдом. Он утянул на дно три лодки — и отпустил только одного рыбака." },

  // ───────────── КОРАЛЛОВЫЙ РИФ (0–60 м) ─────────────
  { id: "clownfish", name: "Рыба-клоун", latin: "Amphiprion ocellaris", loc: ["reef"], depth: [0, 10], rarity: "common", time: "day", weight: [0.01, 0.03], price: 900, strength: 1, shape: "fusiform", colors: { body: "#f07820", belly: "#f8a050", fin: "#f07820", accent: "#ffffff" }, pattern: "bars", bait: ["shrimp"], desc: "Живёт в жгучей актинии и не боится её. Все рождаются самцами." },
  { id: "surgeonfish", name: "Рыба-хирург", latin: "Paracanthurus hepatus", loc: ["reef"], depth: [0, 15], rarity: "common", time: "day", weight: [0.1, 0.6], price: 110, strength: 2, shape: "deep", colors: { body: "#2050c8", belly: "#3868e0", fin: "#f0d020", accent: "#101830" }, pattern: "stripes", bait: ["shrimp"], desc: "У хвоста спрятан острый, как скальпель, шип." },
  { id: "parrotfish", name: "Рыба-попугай", latin: "Scarus guacamaia", loc: ["reef"], depth: [2, 20], rarity: "common", time: "day", weight: [0.8, 6], price: 40, strength: 4, shape: "deep", colors: { body: "#30b090", belly: "#80e0c0", fin: "#e06090", accent: "#f0c040" }, pattern: "spots", bait: ["shrimp", "worm"], desc: "Перемалывает кораллы клювом. Белый песок пляжей — её работа." },
  { id: "angelfish", name: "Рыба-ангел", latin: "Pomacanthus imperator", loc: ["reef"], depth: [5, 25], rarity: "uncommon", time: "day", weather: ["clear"], weight: [0.3, 1.5], price: 130, strength: 3, shape: "deep", colors: { body: "#2040a0", belly: "#f0d040", fin: "#f0d040", accent: "#ffffff" }, pattern: "stripes", bait: ["shrimp"], desc: "Императорская рыба-ангел. Узор меняется с возрастом до неузнаваемости." },
  { id: "moray", name: "Мурена", latin: "Gymnothorax javanicus", loc: ["reef", "volcano"], depth: [5, 45], rarity: "uncommon", time: "night", weight: [2, 20], price: 40, strength: 7, shape: "eel", colors: { body: "#6a6a30", belly: "#a8a060", fin: "#4a4a20" }, pattern: "spots", bait: ["squid", "livebait"], desc: "Вторые челюсти в горле, как у Чужого. Ночью патрулирует риф." },
  { id: "barracuda", name: "Барракуда", latin: "Sphyraena barracuda", loc: ["reef", "mangrove", "ocean"], depth: [0, 30], rarity: "uncommon", time: "any", weight: [2, 18], price: 34, strength: 7, shape: "long", colors: { body: "#7a8a90", belly: "#e8ecee", fin: "#4a5a60" }, pattern: "bars", bait: ["spoon", "wobbler", "livebait"], desc: "Серебряная молния с клыками. Разгоняется до 58 км/ч." },
  { id: "pufferfish", name: "Рыба-ёж", latin: "Diodon holocanthus", loc: ["mangrove", "reef"], depth: [3, 25], rarity: "uncommon", time: "night", weight: [0.3, 2], price: 90, strength: 2, shape: "puffer", colors: { body: "#c8a870", belly: "#f0e8d0", fin: "#8a7040" }, pattern: "spots", bait: ["shrimp"], desc: "Раздувается в колючий шар. Ядовита — не пробовать." },
  { id: "grouper", name: "Групер", latin: "Epinephelus lanceolatus", loc: ["reef"], depth: [15, 60], rarity: "rare", time: "any", weight: [8, 90], price: 30, strength: 9, shape: "deep", colors: { body: "#5a5a38", belly: "#a8a070", fin: "#3a3a20" }, pattern: "spots", bait: ["livebait", "squid"], desc: "Гигантский каменный окунь. Заглатывает добычу целиком вместе с водой." },
  { id: "eagle_ray", name: "Пятнистый орляк", latin: "Aetobatus narinari", loc: ["reef"], depth: [10, 50], rarity: "rare", time: "day", weight: [10, 60], price: 30, strength: 8, shape: "ray", colors: { body: "#2a3a50", belly: "#f0f0f0", fin: "#1a2a40", accent: "#e8e8e8" }, pattern: "spots", bait: ["shrimp", "squid"], desc: "Парит над песком как птица. Иногда выпрыгивает в воздух." },
  { id: "lionfish", name: "Крылатка", latin: "Pterois volitans", loc: ["reef"], depth: [5, 40], rarity: "uncommon", time: "twilight", weight: [0.2, 1.2], price: 110, strength: 3, shape: "deep", colors: { body: "#c84a30", belly: "#f0d0c0", fin: "#e8c0b0", accent: "#ffffff" }, pattern: "bars", bait: ["livebait"], desc: "Веер ядовитых игл. Красота, от которой стоит держаться подальше." },
  { id: "napoleon", name: "Губан-наполеон", latin: "Cheilinus undulatus", loc: ["reef"], depth: [10, 60], rarity: "epic", time: "day", season: [1], weight: [15, 80], price: 50, strength: 8, shape: "deep", colors: { body: "#2a8a8a", belly: "#60c0b0", fin: "#1a6a6a", accent: "#40c0e0" }, pattern: "stripes", bait: ["shrimp", "squid"], desc: "Горб на лбу, как треуголка императора. Узнаёт дайверов в лицо." },
  { id: "golden_moray", name: "Золотая мурена", latin: "Gymnothorax aureus", loc: ["reef"], depth: [20, 60], rarity: "legendary", time: "night", moon: "full", weight: [8, 16], price: 300, strength: 8, shape: "eel", colors: { body: "#e8b830", belly: "#f8e080", fin: "#c89020", accent: "#fff0b0" }, pattern: "spots", glow: "#ffe080", bait: ["squid", "glow"], desc: "Выходит из рифа только в полнолуние. Чешуя светится, как старое золото." },

  // ───────────── ОТКРЫТОЕ МОРЕ (0–420 м) ─────────────
  { id: "yellowfin", name: "Желтопёрый тунец", latin: "Thunnus albacares", loc: ["ocean", "abyss", "volcano"], depth: [0, 150], rarity: "common", time: "day", weight: [10, 90], price: 18, strength: 8, shape: "fusiform", colors: { body: "#1a3a6a", belly: "#e0e8f0", fin: "#f0d020" }, pattern: "gradient", bait: ["livebait", "squid", "wobbler"], desc: "Живая торпеда. Никогда не останавливается — иначе задохнётся." },
  { id: "mahi", name: "Корифена", latin: "Coryphaena hippurus", loc: ["ocean"], depth: [0, 50], rarity: "common", time: "day", season: [1, 2], weight: [3, 20], price: 22, strength: 6, shape: "deep", colors: { body: "#30a060", belly: "#f0e040", fin: "#2060c0", accent: "#40c0f0" }, pattern: "spots", bait: ["wobbler", "spoon"], desc: "Махи-махи. Переливается всеми цветами, а умирая — сереет." },
  { id: "swordfish", name: "Меч-рыба", latin: "Xiphias gladius", loc: ["ocean"], depth: [60, 420], rarity: "rare", time: "night", weight: [40, 300], price: 12, strength: 9, shape: "billfish", colors: { body: "#3a3a4a", belly: "#b0b0c0", fin: "#2a2a38" }, pattern: "gradient", bait: ["squid"], desc: "Греет глаза и мозг особым органом, чтобы охотиться в ледяных глубинах." },
  { id: "blue_marlin", name: "Голубой марлин", latin: "Makaira nigricans", loc: ["ocean"], depth: [0, 200], rarity: "epic", time: "day", weather: ["clear", "cloudy"], weight: [80, 400], price: 10, strength: 10, shape: "billfish", colors: { body: "#1a3a7a", belly: "#e0e8f0", fin: "#1a2a5a", accent: "#60a0e0" }, pattern: "bars", bait: ["livebait", "wobbler"], desc: "Мечта каждого морского рыбака. Бой может длиться часами." },
  { id: "mako", name: "Акула мако", latin: "Isurus oxyrinchus", loc: ["ocean"], depth: [0, 300], rarity: "rare", time: "any", weather: ["cloudy", "rain", "storm"], weight: [60, 400], price: 8, strength: 10, shape: "shark", colors: { body: "#2a4a8a", belly: "#f0f0f4", fin: "#1a3a6a" }, pattern: "gradient", bait: ["livebait", "squid"], desc: "Самая быстрая акула. Выпрыгивает на 6 метров над водой." },
  { id: "wahoo", name: "Ваху", latin: "Acanthocybium solandri", loc: ["volcano", "ocean"], depth: [0, 100], rarity: "uncommon", time: "twilight", weight: [8, 45], price: 20, strength: 7, shape: "long", colors: { body: "#2a5a8a", belly: "#d8e0e8", fin: "#1a3a6a" }, pattern: "bars", bait: ["wobbler", "spoon"], desc: "Бритвенные зубы и рывок, от которого визжит катушка." },
  { id: "sailfish", name: "Парусник", latin: "Istiophorus platypterus", loc: ["ocean"], depth: [0, 100], rarity: "rare", time: "day", season: [1], weight: [20, 90], price: 20, strength: 8, shape: "billfish", colors: { body: "#1a3a6a", belly: "#d8e0ec", fin: "#2a50a0", accent: "#80b0f0" }, pattern: "spots", bait: ["livebait"], desc: "Раскрывает спинной парус, сгоняя сардин в плотный шар." },
  { id: "opah", name: "Опах", latin: "Lampris guttatus", loc: ["ocean"], depth: [50, 420], rarity: "epic", time: "any", weather: ["fog"], weight: [20, 80], price: 30, strength: 7, shape: "deep", colors: { body: "#c05060", belly: "#e8a0a0", fin: "#e03030", accent: "#f0f0f0" }, pattern: "spots", bait: ["squid"], desc: "Единственная полностью теплокровная рыба. Круглая, как луна." },
  { id: "flying_fish", name: "Летучая рыба", latin: "Exocoetus volitans", loc: ["volcano", "ocean"], depth: [0, 6], rarity: "common", time: "day", weight: [0.1, 0.4], price: 100, strength: 2, shape: "fusiform", colors: { body: "#2a5a9a", belly: "#e8f0f8", fin: "#8ab0e0" }, pattern: "gradient", bait: ["shrimp"], desc: "Планирует над волнами до двухсот метров, спасаясь от хищников." },
  { id: "blue_shark", name: "Синяя акула", latin: "Prionace glauca", loc: ["ocean", "kelp"], depth: [0, 350], rarity: "uncommon", time: "night", weight: [30, 150], price: 9, strength: 8, shape: "shark", colors: { body: "#2a60c0", belly: "#f0f4f8", fin: "#1a4aa0" }, pattern: "gradient", bait: ["squid", "livebait"], desc: "Изящная странница океанов. Пересекает Атлантику ради одного свидания." },
  { id: "santiago", name: "Марлин Сантьяго", latin: "Makaira senex", loc: ["ocean"], depth: [20, 250], rarity: "legendary", time: "twilight", weather: ["clear"], weight: [450, 700], price: 12, strength: 10, shape: "billfish", colors: { body: "#2a2a5a", belly: "#c8c8e0", fin: "#1a1a40", accent: "#a080e0" }, pattern: "bars", bait: ["livebait"], desc: "«Старик и море» — не выдумка. Он ждёт на рассвете того, кто не сдастся." },

  // ───────────── БЕЗДНА (0–2000 м) ─────────────
  { id: "hatchetfish", name: "Рыба-топорик", latin: "Argyropelecus aculeatus", loc: ["abyss"], depth: [200, 1000], rarity: "common", time: "any", weight: [0.01, 0.05], price: 1600, strength: 1, shape: "deep", colors: { body: "#a0a8b8", belly: "#e0e8f0", fin: "#606878" }, pattern: "gradient", glow: "#60c0ff", bait: ["glow"], desc: "Светится брюхом, чтобы стереть собственную тень снизу." },
  { id: "deep_angler", name: "Глубоководный удильщик", latin: "Melanocetus johnsonii", loc: ["abyss"], depth: [500, 2000], rarity: "uncommon", time: "any", weight: [0.1, 1], price: 380, strength: 3, shape: "angler", colors: { body: "#1a1a20", belly: "#2a2a30", fin: "#101014" }, pattern: "none", glow: "#80ffe0", bait: ["glow"], desc: "Фонарь на голове манит жертв в пасть. Самец навсегда прирастает к самке." },
  { id: "gulper", name: "Большерот", latin: "Eurypharynx pelecanoides", loc: ["abyss"], depth: [500, 2000], rarity: "rare", time: "any", weight: [0.5, 2], price: 400, strength: 4, shape: "eel", colors: { body: "#1a1418", belly: "#2a2028", fin: "#100c10" }, pattern: "none", glow: "#ff60a0", bait: ["glow", "shrimp"], desc: "Пеликановый угорь: рот больше тела, на хвосте — розовый огонёк." },
  { id: "giant_squid", name: "Гигантский кальмар", latin: "Architeuthis dux", loc: ["abyss"], depth: [300, 1500], rarity: "epic", time: "night", weight: [100, 275], price: 16, strength: 10, shape: "squid", colors: { body: "#a03a2a", belly: "#d07060", fin: "#702418" }, pattern: "spots", bait: ["squid", "glow"], desc: "Глаза размером с тарелку. Кракен из морских легенд — реален." },
  { id: "blobfish", name: "Рыба-капля", latin: "Psychrolutes marcidus", loc: ["abyss"], depth: [600, 1500], rarity: "uncommon", time: "any", weight: [1, 3], price: 180, strength: 2, shape: "blob", colors: { body: "#e0a0a0", belly: "#f0c8c8", fin: "#c08080" }, pattern: "none", bait: ["worm", "shrimp"], desc: "На глубине — обычная рыба. На поверхности — самое грустное лицо в мире." },
  { id: "ghost_chimaera", name: "Химера-призрак", latin: "Hydrolagus trolli", loc: ["abyss"], depth: [500, 1800], rarity: "rare", time: "any", weather: ["fog"], weight: [1, 5], price: 220, strength: 5, shape: "long", colors: { body: "#c8c8d0", belly: "#e8e8f0", fin: "#a0a0b0" }, pattern: "none", glow: "#c0d0ff", bait: ["glow"], desc: "Бледный призрак, впервые снятый на камеру лишь в 2016 году." },
  { id: "goblin_shark", name: "Акула-домовой", latin: "Mitsukurina owstoni", loc: ["abyss"], depth: [300, 1300], rarity: "epic", time: "night", weight: [80, 210], price: 14, strength: 9, shape: "shark", colors: { body: "#d8a0a0", belly: "#f0d0d0", fin: "#b07878" }, pattern: "none", bait: ["squid"], desc: "Челюсти выстреливают вперёд, как катапульта. Живое ископаемое." },
  { id: "oarfish", name: "Сельдяной король", latin: "Regalecus glesne", loc: ["abyss"], depth: [200, 1000], rarity: "epic", time: "any", weather: ["storm"], weight: [50, 270], price: 16, strength: 8, shape: "eel", colors: { body: "#d0d8e0", belly: "#f0f4f8", fin: "#e03040", accent: "#80a0c0" }, pattern: "spots", bait: ["shrimp", "glow"], desc: "Ремнетел длиной до 11 метров. Японцы верят — он предвещает землетрясения." },
  { id: "leviathan", name: "Тот, что внизу", latin: "Leviathan profundus", loc: ["abyss"], depth: [1700, 2000], rarity: "legendary", time: "night", weather: ["storm"], weight: [900, 1500], price: 12, strength: 10, shape: "angler", colors: { body: "#0c1018", belly: "#1a2230", fin: "#060810", accent: "#40ffd0" }, pattern: "spots", glow: "#40ffd0", bait: ["glow"], desc: "У него нет латинского имени — только догадки. Приходит в штормовую ночь на свет самой глубокой приманки." },
];

const LOC_ORDER = ["bay", "estuary", "cape", "skerries", "fjord", "kelp", "reef", "mangrove", "ocean", "volcano", "abyss", "antarctic"];
const RAR_ORDER = ["common", "uncommon", "rare", "epic", "legendary"];
/** Весь кодекс, упорядоченный по акватории и редкости */
export const FISH: FishDef[] = [...FISH_BASE, ...FISH_EXTRA, ...FISH_VOL3, ...FISH_VOL4, ...FISH_VOL5]
  .map((f, i) => ({ f, i }))
  .sort((a, b) => LOC_ORDER.indexOf(a.f.loc[0]) - LOC_ORDER.indexOf(b.f.loc[0]) || RAR_ORDER.indexOf(a.f.rarity) - RAR_ORDER.indexOf(b.f.rarity) || a.i - b.i)
  .map((x) => x.f);
ensureDistinct(FISH);
export const FISH_TOTAL = FISH.length;

export const FISH_BY_ID: Record<string, FishDef> = Object.fromEntries(FISH.map((f) => [f.id, f]));

/**
 * Редкость вида.
 *
 * `base` — ставка за одну рыбу в рублях: её платят независимо от веса, даже за
 * мелкую. Без неё бычок на 50 граммов стоил пару рублей, и улов не окупал
 * приманку. К ставке сверху добавляется вес по цене за килограмм.
 */
export const RARITY_INFO = {
  common: { name: "Обычная", color: "#a9b4ba", weight: 100, bonus: 25, base: 35 },
  uncommon: { name: "Необычная", color: "#8dbb98", weight: 38, bonus: 60, base: 50 },
  rare: { name: "Редкая", color: "#83acd0", weight: 12, bonus: 150, base: 70 },
  epic: { name: "Исключительная", color: "#ad96c8", weight: 3.5, bonus: 400, base: 110 },
  legendary: { name: "Легендарная", color: "#d7b46e", weight: 1.2, bonus: 1500, base: 200 },
} as const;

export const VARIANT_INFO = {
  albino: { name: "Альбинос", mult: 3, color: "#e6e1d6" },
  golden: { name: "Золотая", mult: 6, color: "#d7b46e" },
  melanist: { name: "Меланист", mult: 2.5, color: "#8a8fa8" },
  scarred: { name: "Со шрамами", mult: 1.6, color: "#b89080" },
  trophy: { name: "Трофейная", mult: 2, color: "#d49a72" },
} as const;
