import type { FishDef } from "./types";

// Пятый том кодекса: 46 видов
export const FISH_VOL5: FishDef[] = [
  // ───────────── ТИХАЯ БУХТА ─────────────
  { id: "gilthead", name: "Дорада", latin: "Sparus aurata", loc: ["bay"], depth: [2, 18], rarity: "uncommon", time: "day", weather: ["clear", "cloudy"], weight: [0.4, 3], price: 95, strength: 4, shape: "deep", colors: { body: "#b0b4b0", belly: "#eceee8", fin: "#6a6e6a", accent: "#e0b030" }, pattern: "gradient", bait: ["mussel", "shrimp"], desc: "Золотая полоска между глаз, словно брошь. Мощными челюстями раскалывает мидий и крабов — одна из самых ценимых рыб Средиземноморья." },
  { id: "pipefish", name: "Морская игла", latin: "Syngnathus typhle", loc: ["bay"], depth: [1, 10], rarity: "common", time: "day", weight: [0.005, 0.03], price: 900, strength: 1, shape: "long", colors: { body: "#6a7a3a", belly: "#a8b070", fin: "#4a5a2a" }, pattern: "stripes", bait: ["shrimp"], desc: "Родственница морского конька, вытянутая в соломинку. Неотличима от стеблей взморника, среди которых качается." },
  { id: "shi_drum", name: "Горбыль светлый", latin: "Umbrina cirrosa", loc: ["bay"], depth: [3, 16], rarity: "rare", time: "twilight", weight: [1, 6], price: 110, strength: 5, shape: "fusiform", colors: { body: "#a89a70", belly: "#ece4c8", fin: "#6a5e40", accent: "#4a4a6a" }, pattern: "stripes", bait: ["shrimp", "livebait"], desc: "Серебристо-золотой горбыль с короткой бородкой. Урчит плавательным пузырём, и в тихие вечера его слышно из лодки." },

  // ───────────── ЛИМАН ─────────────
  { id: "tench", name: "Линь", latin: "Tinca tinca", loc: ["estuary"], depth: [1, 6], rarity: "uncommon", time: "twilight", season: [1], weight: [0.4, 3], price: 70, strength: 4, shape: "deep", colors: { body: "#4a5a2a", belly: "#b8a860", fin: "#2a3a1a", accent: "#e08a30" }, pattern: "none", bait: ["worm"], desc: "Бархатистая оливковая рыба с красными глазами. Слизь линя в старину считали целебной для других рыб." },
  { id: "crucian", name: "Золотой карась", latin: "Carassius carassius", loc: ["estuary"], depth: [0, 5], rarity: "common", time: "day", weight: [0.1, 1], price: 55, strength: 2, shape: "deep", colors: { body: "#b8943a", belly: "#e8d890", fin: "#8a6a2a" }, pattern: "none", bait: ["worm"], desc: "Неприхотливый житель заводей, переживающий даже промерзание до дна. Клюёт осторожно, долго водя поплавок." },
  { id: "gudgeon", name: "Пескарь", latin: "Gobio gobio", loc: ["estuary"], depth: [0, 4], rarity: "common", time: "day", weight: [0.01, 0.06], price: 350, strength: 1, shape: "fusiform", colors: { body: "#7a7a60", belly: "#dcd8c0", fin: "#5a5a44" }, pattern: "spots", bait: ["worm"], desc: "Маленькая донная рыбка с усиками. Держится стайками на песчаных перекатах и первым хватает червя." },
  { id: "sterlet", name: "Стерлядь", latin: "Acipenser ruthenus", loc: ["estuary"], depth: [4, 12], rarity: "epic", time: "night", season: [0, 2], weight: [1, 6], price: 280, strength: 5, shape: "long", colors: { body: "#6a6458", belly: "#e8d8b0", fin: "#4a443a", accent: "#e8d8b0" }, pattern: "spots", bait: ["worm", "mussel"], desc: "Самый маленький осётр с бахромчатыми усиками. Её уха когда-то была символом царского стола." },

  // ───────────── СКАЛИСТЫЙ МЫС ─────────────
  { id: "cuckoo_ray", name: "Скат-кукушка", latin: "Leucoraja naevus", loc: ["cape"], depth: [20, 45], rarity: "uncommon", time: "any", weight: [0.8, 3], price: 45, strength: 3, shape: "ray", colors: { body: "#9a7a4a", belly: "#f0ece0", fin: "#7a5a34", accent: "#1a1a1a" }, pattern: "spots", bait: ["cutbait", "shrimp"], desc: "На каждом крыле — чёрно-жёлтое «око», отпугивающее хищников. Живёт на песке у подножия скал." },
  { id: "tub_gurnard", name: "Тригла жёлтая", latin: "Chelidonichthys obscurus", loc: ["cape"], depth: [10, 40], rarity: "common", time: "day", weight: [0.2, 1], price: 60, strength: 2, shape: "fusiform", colors: { body: "#c86a3a", belly: "#f0c8a0", fin: "#e0c040", accent: "#4a80c0" }, pattern: "gradient", bait: ["shrimp", "worm"], desc: "Раскрывает грудные плавники, как бабочка крылья, и шагает по дну. Меньше морского петуха, но ярче." },
  { id: "black_seabream", name: "Кантар", latin: "Spondyliosoma cantharus", loc: ["cape"], depth: [5, 35], rarity: "common", time: "any", weight: [0.3, 1.5], price: 55, strength: 3, shape: "deep", colors: { body: "#5a6070", belly: "#b8bcc4", fin: "#3a404a" }, pattern: "stripes", bait: ["mussel", "shrimp"], desc: "Тёмный спар с тонкими золотистыми полосками. Самцы роют на дне ямки-гнёзда и охраняют икру." },
  { id: "angel_shark", name: "Морской ангел", latin: "Squatina squatina", loc: ["cape"], depth: [20, 45], rarity: "epic", time: "night", weight: [15, 60], price: 20, strength: 7, shape: "ray", colors: { body: "#7a6a50", belly: "#e0dcd0", fin: "#5a4a34" }, pattern: "spots", bait: ["livebait", "cutbait"], desc: "Акула, похожая на ската. Лежит в песке и молниеносно выбрасывает челюсти вверх. Почти исчезла у европейских берегов." },

  // ───────────── ШХЕРЫ ─────────────
  { id: "roach_baltic", name: "Плотва", latin: "Rutilus rutilus", loc: ["skerries"], depth: [0, 8], rarity: "common", time: "any", weight: [0.05, 0.5], price: 60, strength: 1, shape: "fusiform", colors: { body: "#8a9aa4", belly: "#f0f2f0", fin: "#d85a3a" }, pattern: "gradient", bait: ["worm"], desc: "Серебристая рыбка с красными глазами — самая массовая в солоноватых бухтах Балтики." },
  { id: "silver_bream", name: "Густера", latin: "Blicca bjoerkna", loc: ["skerries"], depth: [2, 12], rarity: "common", time: "twilight", weight: [0.1, 0.6], price: 55, strength: 2, shape: "deep", colors: { body: "#a8acb0", belly: "#eceef0", fin: "#c87a5a" }, pattern: "none", bait: ["worm", "mussel"], desc: "Похожа на молодого леща, но с розоватыми плавниками. Держится плотными стаями у тростниковых зарослей." },
  { id: "grayling", name: "Хариус", latin: "Thymallus thymallus", loc: ["skerries"], depth: [0, 10], rarity: "rare", time: "day", season: [0, 2], weight: [0.3, 1.5], price: 260, strength: 3, shape: "fusiform", colors: { body: "#6a7080", belly: "#e0e4e8", fin: "#8a5a8a", accent: "#e04a6a" }, pattern: "spots", bait: ["spoon", "worm"], desc: "Высокий спинной плавник-парус в фиолетовых и алых пятнах. Выходит из рек в опреснённые бухты лишь весной и осенью." },

  // ───────────── СЕВЕРНЫЙ ФЬОРД ─────────────
  { id: "sprat_nor", name: "Шпрот", latin: "Sprattus sprattus", loc: ["fjord"], depth: [0, 60], rarity: "common", time: "any", weight: [0.005, 0.02], price: 450, strength: 1, shape: "fusiform", colors: { body: "#4a6a7a", belly: "#f0f4f4", fin: "#5a7a8a" }, pattern: "gradient", bait: ["shrimp"], desc: "Та самая рыбка из консервной банки. Громадные стаи шпрота держатся в верхнем слое фьорда." },
  { id: "norway_pout", name: "Норвежская тресочка", latin: "Trisopterus esmarkii", loc: ["fjord"], depth: [50, 160], rarity: "common", time: "any", weight: [0.03, 0.2], price: 110, strength: 1, shape: "fusiform", colors: { body: "#9a8a6a", belly: "#ece4d0", fin: "#6a5a40" }, pattern: "none", bait: ["shrimp", "worm"], desc: "Мелкая треска глубин, основа питания пикши и сайды. Большие глаза выдают жителя сумрака." },
  { id: "lemon_sole", name: "Лиманда", latin: "Microstomus kitt", loc: ["fjord"], depth: [20, 120], rarity: "uncommon", time: "any", weight: [0.3, 1.5], price: 90, strength: 2, shape: "flat", colors: { body: "#8a7040", belly: "#f4ecd8", fin: "#6a5430", accent: "#e8c050" }, pattern: "spots", bait: ["worm"], desc: "Гладкая, как шёлк, камбала в мраморных разводах. Маленький рот выдаёт любительницу мелких червей." },
  { id: "black_scabbard", name: "Чёрная рыба-сабля", latin: "Aphanopus carbo", loc: ["fjord"], depth: [120, 160], rarity: "rare", time: "night", weight: [1.5, 4], price: 140, strength: 5, shape: "long", colors: { body: "#1e1e24", belly: "#3a3a44", fin: "#101014", accent: "#8a6a4a" }, pattern: "none", bait: ["cutbait", "squid"], desc: "Длинная медно-чёрная лента с огромными глазами и клыками. Поднимается к краю глубин только по ночам." },

  // ───────────── ТУМАННЫЙ БЕРЕГ ─────────────
  { id: "kelp_greenling", name: "Зеленопёрый терпуг", latin: "Hexagrammos decagrammus", loc: ["kelp"], depth: [2, 30], rarity: "common", time: "day", weight: [0.3, 1.5], price: 60, strength: 3, shape: "fusiform", colors: { body: "#7a6040", belly: "#d8c8a0", fin: "#5a4a2e", accent: "#4a80c0" }, pattern: "spots", bait: ["shrimp", "mussel"], desc: "Самцы усыпаны голубыми пятнами, самки — рыжими. Терпуги строго охраняют свой участок водорослевого леса." },
  { id: "treefish", name: "Древесный окунь", latin: "Sebastes serriceps", loc: ["kelp"], depth: [5, 40], rarity: "uncommon", time: "night", weight: [0.3, 1.2], price: 90, strength: 3, shape: "deep", colors: { body: "#d8b040", belly: "#f0d880", fin: "#1a1a1a", accent: "#e0402a" }, pattern: "bars", bait: ["shrimp"], desc: "Жёлтый окунь в широких чёрных полосах, с алыми губами. Прячется в расщелинах и выходит только ночью." },
  { id: "pacific_bonito", name: "Тихоокеанская пеламида", latin: "Sarda chiliensis", loc: ["kelp"], depth: [0, 40], rarity: "uncommon", time: "day", season: [1, 2], weight: [1, 5], price: 55, strength: 6, shape: "fusiform", colors: { body: "#2a4a6a", belly: "#e0e8ee", fin: "#1a3a5a" }, pattern: "stripes", bait: ["spoon", "wobbler"], desc: "Налетает на стаи анчоуса у края водорослей. Летом вода над лесом кипит от её атак." },
  { id: "white_sturgeon", name: "Белый осётр", latin: "Acipenser transmontanus", loc: ["kelp"], depth: [10, 60], rarity: "epic", time: "twilight", weather: ["fog", "rain"], weight: [60, 250], price: 25, strength: 9, shape: "long", colors: { body: "#6a6e70", belly: "#e0e4e4", fin: "#4a4e50", accent: "#c8ccc8" }, pattern: "spots", bait: ["cutbait", "squid"], desc: "Крупнейшая рыба тихоокеанского побережья, способная прожить сто лет. Заходит из рек в туманные бухты." },

  // ───────────── КОРАЛЛОВЫЙ РИФ ─────────────
  { id: "mandarin", name: "Рыба-мандаринка", latin: "Synchiropus splendidus", loc: ["reef"], depth: [1, 18], rarity: "rare", time: "twilight", weight: [0.005, 0.02], price: 9000, strength: 1, shape: "fusiform", colors: { body: "#2a60c0", belly: "#e08a30", fin: "#f0a040", accent: "#40c080" }, pattern: "spots", bait: ["shrimp"], desc: "Одна из немногих животных, окрашенных настоящим синим пигментом. Выходит из кораллов только на закате для брачного танца." },
  { id: "flame_angel", name: "Огненный ангел", latin: "Centropyge loriculus", loc: ["reef"], depth: [5, 30], rarity: "uncommon", time: "day", weight: [0.01, 0.05], price: 2400, strength: 1, shape: "deep", colors: { body: "#e8402a", belly: "#f08040", fin: "#2a2aa0", accent: "#1a1a4a" }, pattern: "bars", bait: ["shrimp"], desc: "Карликовая рыба-ангел цвета пламени с синей каймой плавников. Живёт гаремом: один самец и несколько самок." },
  { id: "squirrelfish", name: "Рыба-белка", latin: "Sargocentron spiniferum", loc: ["reef"], depth: [2, 30], rarity: "common", time: "night", weight: [0.2, 1.5], price: 70, strength: 2, shape: "deep", colors: { body: "#d8402a", belly: "#f0a080", fin: "#f0d0c0", accent: "#ffffff" }, pattern: "stripes", bait: ["shrimp"], desc: "Огромные глаза и острые шипы на жаберных крышках. Днём стоит в тени кораллов, ночью выходит кормиться." },
  { id: "dogtooth", name: "Собачезубый тунец", latin: "Gymnosarda unicolor", loc: ["reef"], depth: [10, 60], rarity: "epic", time: "twilight", weight: [20, 80], price: 18, strength: 9, shape: "fusiform", colors: { body: "#3a4a60", belly: "#dfe4ea", fin: "#2a3444" }, pattern: "gradient", bait: ["jig", "livebait"], desc: "Тунец рифовых стен с конической пастью, полной клыков. Бросается на джиг с глубины и уходит обратно в кораллы." },

  { id: "harlequin_tusk", name: "Рыба-арлекин", latin: "Choerodon fasciatus", loc: ["reef"], depth: [5, 35], rarity: "rare", time: "day", weather: ["clear"], weight: [0.5, 2.5], price: 220, strength: 4, shape: "deep", colors: { body: "#f0f0e8", belly: "#fff8f0", fin: "#2a60c0", accent: "#e8602a" }, pattern: "bars", bait: ["shrimp", "mussel"], desc: "Оранжевые полосы на белом, синие плавники и ярко-синие клыки, которыми губан переворачивает камни в поисках крабов." },

  // ───────────── МАНГРОВЫЕ ПРОТОКИ ─────────────
  { id: "scat", name: "Скатофаг", latin: "Scatophagus argus", loc: ["mangrove"], depth: [0, 8], rarity: "common", time: "day", weight: [0.05, 0.5], price: 180, strength: 2, shape: "deep", colors: { body: "#9a8a4a", belly: "#d8c890", fin: "#6a5a2a", accent: "#2a2a1a" }, pattern: "spots", bait: ["worm", "shrimp"], desc: "Округлая пятнистая рыба, поедающая всё — от водорослей до отходов. Легко переходит из морской воды в пресную." },
  { id: "barramundi", name: "Баррамунди", latin: "Lates calcarifer", loc: ["mangrove"], depth: [1, 16], rarity: "rare", time: "twilight", weight: [3, 25], price: 45, strength: 7, shape: "fusiform", colors: { body: "#8a8a7a", belly: "#ece8dc", fin: "#5a5a4a" }, pattern: "gradient", bait: ["livebait", "wobbler"], desc: "Серебряный окунь с красными глазами, светящимися в свете фонаря. Все особи рождаются самцами и с возрастом становятся самками." },
  { id: "halfbeak", name: "Полурыл", latin: "Hemiramphus brasiliensis", loc: ["mangrove"], depth: [0, 3], rarity: "common", time: "day", weight: [0.05, 0.2], price: 200, strength: 1, shape: "long", colors: { body: "#4a7a9a", belly: "#e8f0f4", fin: "#3a5a70", accent: "#e04030" }, pattern: "gradient", bait: ["shrimp"], desc: "Нижняя челюсть вытянута в длинный клюв, а верхняя — короткая. Скользит у самой поверхности протоки." },

  // ───────────── ОТКРЫТОЕ МОРЕ ─────────────
  { id: "pilot_fish", name: "Рыба-лоцман", latin: "Naucrates ductor", loc: ["ocean"], depth: [0, 50], rarity: "uncommon", time: "day", weight: [0.3, 1.5], price: 110, strength: 3, shape: "fusiform", colors: { body: "#6a7a90", belly: "#d8e0e8", fin: "#2a3444", accent: "#1a2030" }, pattern: "bars", bait: ["shrimp", "spoon"], desc: "Сопровождает акул и черепах, держась у самой морды хозяина. Моряки верили, что она прокладывает путь кораблям." },
  { id: "tripletail", name: "Трёххвост", latin: "Lobotes surinamensis", loc: ["ocean"], depth: [0, 30], rarity: "rare", time: "day", weight: [2, 12], price: 60, strength: 5, shape: "deep", colors: { body: "#6a5a3a", belly: "#a89a70", fin: "#4a3e28" }, pattern: "spots", bait: ["shrimp", "livebait"], desc: "Лежит на боку у поверхности под плавающими обломками, притворяясь сухим листом. Кажется, что хвостов у неё три." },
  { id: "whale_shark", name: "Китовая акула", latin: "Rhincodon typus", loc: ["ocean"], depth: [0, 150], rarity: "legendary", time: "day", season: [1], weather: ["clear"], weight: [4000, 9000], price: 0.4, strength: 10, shape: "shark", colors: { body: "#3a4a60", belly: "#e8ecf0", fin: "#2a3444", accent: "#e8ecf0" }, pattern: "spots", bait: ["shrimp"], desc: "Крупнейшая рыба на Земле, мирно процеживающая планктон. Взять её на снасть почти невозможно — после снимка лучше отпустить." },

  // ───────────── ВУЛКАНИЧЕСКИЙ АРХИПЕЛАГ ─────────────
  { id: "picasso_trigger", name: "Спинорог-Пикассо", latin: "Rhinecanthus aculeatus", loc: ["volcano"], depth: [0, 15], rarity: "uncommon", time: "day", weight: [0.2, 0.6], price: 300, strength: 2, shape: "deep", colors: { body: "#d8ccb0", belly: "#f4ecd8", fin: "#e0c040", accent: "#2a50a0" }, pattern: "stripes", bait: ["shrimp", "mussel"], desc: "Будто раскрашен кистью художника-авангардиста: голубые и жёлтые полосы, чёрные пятна. Громко хрюкает, когда его ловят." },
  { id: "bluestripe_snapper", name: "Голубополосый луциан", latin: "Lutjanus kasmira", loc: ["volcano"], depth: [5, 90], rarity: "common", time: "any", weight: [0.1, 0.5], price: 120, strength: 2, shape: "fusiform", colors: { body: "#e8c040", belly: "#f8e8a0", fin: "#e0b030", accent: "#40a0e0" }, pattern: "stripes", bait: ["shrimp", "jig"], desc: "Жёлтый луциан с четырьмя голубыми полосами. Держится огромными стаями у лавовых выступов." },
  { id: "deep_bigeye", name: "Большеглазый тунец", latin: "Thunnus obesus", loc: ["volcano"], depth: [60, 500], rarity: "epic", time: "night", weight: [40, 180], price: 22, strength: 10, shape: "fusiform", colors: { body: "#1a2a50", belly: "#dfe4ee", fin: "#e0c040" }, pattern: "gradient", bait: ["squid", "jig"], desc: "Глаза огромные, чтобы охотиться в полумраке глубин. Днём уходит на полкилометра, ночью поднимается к кальдере." },

  // ───────────── БЕЗДНА ─────────────
  { id: "cookiecutter", name: "Бразильская светящаяся акула", latin: "Isistius brasiliensis", loc: ["abyss"], depth: [200, 1000], rarity: "rare", time: "night", weight: [0.2, 0.8], price: 900, strength: 3, shape: "shark", colors: { body: "#5a4a40", belly: "#8a7a6a", fin: "#3a2e26" }, pattern: "none", glow: "#60c0a0", bait: ["glow", "cutbait"], desc: "Маленькая акула, вырезающая идеально круглые куски из тел китов и тунцов. Светится всем брюхом, кроме тёмного «ошейника»." },
  { id: "loosejaw", name: "Малакост", latin: "Malacosteus niger", loc: ["abyss"], depth: [500, 2000], rarity: "uncommon", time: "any", weight: [0.01, 0.05], price: 3000, strength: 1, shape: "long", colors: { body: "#0e0e12", belly: "#1a1a20", fin: "#08080a" }, pattern: "none", glow: "#ff4040", bait: ["glow"], desc: "Челюсть без дна — между костями нет кожи. Светит красным фонарём, которого не видят другие глубоководные." },
  { id: "hagfish", name: "Миксина", latin: "Myxine glutinosa", loc: ["abyss"], depth: [300, 1200], rarity: "common", time: "any", weight: [0.05, 0.3], price: 400, strength: 2, shape: "eel", colors: { body: "#c89090", belly: "#e0b0b0", fin: "#a87070" }, pattern: "none", bait: ["cutbait", "worm"], desc: "Бесчелюстная, слепая, выделяет вёдра слизи. Завязывается узлом, чтобы оторвать кусок от падали." },
  { id: "abyss_snail", name: "Рыба-слизень Мариан", latin: "Pseudoliparis swirei", loc: ["abyss"], depth: [1500, 2000], rarity: "epic", time: "any", weight: [0.05, 0.2], price: 4500, strength: 1, shape: "blob", colors: { body: "#e8d0d0", belly: "#f4e4e4", fin: "#d8b8b8" }, pattern: "none", bait: ["shrimp", "glow"], desc: "Самая глубоководная рыба планеты. Полупрозрачная и розовая, будто сделана из желе. Выдерживает давление в тысячу атмосфер." },

  { id: "gulper_shark", name: "Колючая глубоководная акула", latin: "Centrophorus granulosus", loc: ["abyss"], depth: [200, 1400], rarity: "uncommon", time: "any", weight: [3, 12], price: 60, strength: 5, shape: "shark", colors: { body: "#5a5048", belly: "#8a8074", fin: "#3a3430" }, pattern: "none", bait: ["cutbait", "squid"], desc: "Акула с изумрудными светящимися глазами и шипами перед спинными плавниками. Вынашивает всего одного детёныша за два года." },

  // ───────────── ЛЕДЯНОЙ ШЕЛЬФ ─────────────
  { id: "ice_pout", name: "Антарктическая бельдюговая", latin: "Lycodichthys dearborni", loc: ["antarctic"], depth: [0, 400], rarity: "common", time: "any", weight: [0.05, 0.3], price: 260, strength: 1, shape: "eel", colors: { body: "#a89a88", belly: "#d8ccbc", fin: "#887a68" }, pattern: "none", bait: ["worm", "shrimp"], desc: "Небольшая рыба-угорь, чья кровь содержит белки-антифризы. Лежит в донном иле под морским льдом." },
  { id: "unicorn_icefish", name: "Ледяная рыба-единорог", latin: "Channichthys rhinoceratus", loc: ["antarctic"], depth: [50, 600], rarity: "rare", time: "night", weight: [0.3, 1.5], price: 260, strength: 3, shape: "long", colors: { body: "#c0ccd0", belly: "#e4ecf0", fin: "#98a8b0", accent: "#4a6a8a" }, pattern: "spots", bait: ["cutbait", "shrimp"], desc: "На рыле — маленький рог. Как и другие белокровки, лишена гемоглобина: жабры у неё белые, а кровь прозрачна." },
  { id: "marbled_plunderfish", name: "Мраморная харпагифера", latin: "Pogonophryne marmorata", loc: ["antarctic"], depth: [300, 1200], rarity: "uncommon", time: "any", weight: [0.1, 0.6], price: 700, strength: 2, shape: "angler", colors: { body: "#6a5a4a", belly: "#b8a890", fin: "#4a3e30", accent: "#e8e0d0" }, pattern: "spots", bait: ["shrimp", "glow"], desc: "Большеголовая рыба-бородач с приманкой-усиком под подбородком. Сидит на дне в засаде месяцами." },
  { id: "southern_right_mola", name: "Южная луна-рыба", latin: "Mola alexandrini", loc: ["antarctic", "ocean"], depth: [20, 500], rarity: "epic", time: "day", weather: ["clear", "cloudy"], weight: [300, 1800], price: 2, strength: 8, shape: "deep", colors: { body: "#9aa4ac", belly: "#dfe4e8", fin: "#7a848c" }, pattern: "spots", bait: ["squid"], desc: "Самая тяжёлая костная рыба мира. Из холодных вод поднимается к поверхности погреться, чтобы нырнуть снова." },
  { id: "white_icefish_king", name: "Король подо льдом", latin: "Dissostichus rex", loc: ["antarctic"], depth: [900, 1200], rarity: "legendary", time: "night", weather: ["snow"], weight: [180, 260], price: 30, strength: 10, shape: "fusiform", colors: { body: "#e8eef2", belly: "#ffffff", fin: "#b8c8d4", accent: "#80a8c8" }, pattern: "none", bait: ["squid", "cutbait"], desc: "Белый клыкач-великан, которого полярники описывают как призрак. Поднимается из полыньи только в метель." },
];
