import type { EventCtx, EventDef, EventTier, Outcome } from './types';

/* ─────────────── хелперы условий ─────────────── */

const ss = (a: number, b: number, x: number) => {
  const t = Math.max(0, Math.min(1, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
};
const isNight = (c: EventCtx) => c.night;
const isDay = (c: EventCtx) => c.daylight;
const calm = (c: EventCtx) => 1 - ss(6, 12, c.wind);
const stormy = (c: EventCtx) => (c.kind === 'storm' || c.kind === 'gale' || c.kind === 'blizzard' ? 1 : 0);
const warm = (c: EventCtx) => ss(10, 20, c.temp);
const cold = (c: EventCtx) => ss(4, -4, c.temp);
const cl = (c: EventCtx, m: Partial<Record<EventCtx['climate'], number>>) => m[c.climate] ?? 0;
const season = (c: EventCtx, m: [number, number, number, number]) => m[c.season];
const fullMoon = (c: EventCtx) => ss(0.85, 0.98, c.moonIllum);
const newMoon = (c: EventCtx) => ss(0.15, 0.03, c.moonIllum);
const noStorm = (c: EventCtx) => 1 - stormy(c);
const twilight = (c: EventCtx) => ss(-8, -2, c.sunElev) * (1 - ss(4, 9, c.sunElev));
const r = (rnd: () => number, a: number, b: number) => Math.round(a + rnd() * (b - a));

export const TIER_INFO: Record<EventTier, { name: string; color: string; weight: number }> = {
  common: { name: 'Обычное', color: '#b9c3c9', weight: 10 },
  uncommon: { name: 'Необычное', color: '#86b494', weight: 5 },
  rare: { name: 'Редкое', color: '#6fa8dc', weight: 2.2 },
  epic: { name: 'Исключительное', color: '#b48ee0', weight: 0.9 },
  legendary: { name: 'Легендарное', color: '#e3b45a', weight: 0.35 },
  mythic: { name: 'Мифическое', color: '#ff7a6b', weight: 0.12 },
};

export const CATEGORY_INFO: Record<EventDef['cat'], { name: string; icon: string }> = {
  fish: { name: 'Рыба', icon: '🐟' },
  life: { name: 'Обитатели', icon: '🐬' },
  sky: { name: 'Небо', icon: '✨' },
  mystic: { name: 'Тайны', icon: '🕯️' },
  hazard: { name: 'Стихия', icon: '⚠️' },
  find: { name: 'Находки', icon: '🍾' },
  people: { name: 'Люди', icon: '⛵' },
};

/* ─────────────── каталог ─────────────── */

export const EVENTS: EventDef[] = [
  /* ═══════════ РЫБА ═══════════ */
  {
    id: 'shoal',
    name: 'Косяк рыбы',
    icon: '🐟',
    tier: 'common',
    cat: 'fish',
    desc: 'Вода закипела — под лодкой идёт огромная стая!',
    duration: [30, 60],
    when: (c) => noStorm(c) * (0.6 + c.daylight * 0.4),
    effects: { bite: 2.2 },
    fx: [{ id: 'boil' }],
    follow: [
      { id: 'dolphins', chance: 0.22, delay: [5, 20] },
      { id: 'orcas', chance: 0.05, delay: [10, 25] },
    ],
    outro: 'Стая ушла на глубину.',
  },
  {
    id: 'gulls',
    name: 'Чайки над водой',
    icon: '🕊️',
    tier: 'common',
    cat: 'fish',
    desc: 'Птицы кружат и ныряют — рыба у самой поверхности.',
    duration: [40, 80],
    when: (c) => isDay(c) * noStorm(c) * (1 - c.fog) * (c.loc === 'abyss' ? 0 : 1),
    effects: { bite: 1.5 },
    omen: { text: 'У горизонта собираются чайки…', lead: [6, 14] },
    fx: [{ id: 'birds' }],
    follow: [{ id: 'shoal', chance: 0.45, delay: [3, 10] }],
  },
  {
    id: 'baitball',
    name: 'Шар сардины',
    icon: '🌀',
    tier: 'uncommon',
    cat: 'fish',
    desc: 'Хищники сбили мелочь в плотный шар. Над водой — птичий базар, под водой — пир.',
    duration: [20, 40],
    when: (c) => noStorm(c) * isDay(c) * (cl(c, { ocean: 1.6, tropic: 1.4, temperate: 0.9, misty: 1 }) || 0) * season(c, [0.6, 1.5, 1.1, 0.2]),
    effects: { bite: 2.6, rare: 1.3 },
    fx: [{ id: 'boil', n: 2 }, { id: 'birds', n: 2 }],
    follow: [
      { id: 'sharks', chance: 0.3, delay: [5, 15] },
      { id: 'dolphins', chance: 0.3, delay: [2, 10] },
    ],
    major: true,
  },
  {
    id: 'tuna_blitz',
    name: 'Котёл тунца',
    icon: '💥',
    tier: 'rare',
    cat: 'fish',
    desc: 'Тунцы гонят стаю к поверхности — вода взрывается фонтанами брызг.',
    duration: [15, 35],
    when: (c) => noStorm(c) * (cl(c, { ocean: 1.8, tropic: 1.3, misty: 0.6 }) || 0) * season(c, [0.4, 1.4, 1.2, 0.1]) * (0.5 + isDay(c)),
    effects: { bite: 2, rare: 1.6 },
    fx: [{ id: 'boil', n: 3 }, { id: 'jumpers', n: 1 }, { id: 'birds' }],
    major: true,
  },
  {
    id: 'current',
    name: 'Холодное течение',
    icon: '🌊',
    tier: 'uncommon',
    cat: 'fish',
    desc: 'Апвеллинг поднял холодную воду из глубин — с ней пришли глубинные виды.',
    duration: [60, 120],
    when: (c) => 0.6 + (c.deep ? 0.6 : 0) + cl(c, { misty: 0.6, ocean: 0.4, north: 0.3 }),
    effects: { rare: 1.5, bite: 1.1 },
    atmo: { fog: 0.18 },
    fx: [{ id: 'current' }],
  },
  {
    id: 'herring_spawn',
    name: 'Нерест сельди',
    icon: '🥛',
    tier: 'uncommon',
    cat: 'fish',
    desc: 'Вода у берега помутнела от молок — сельдь мечет икру, и за ней пришли все хищники округи.',
    duration: [90, 180],
    when: (c) => season(c, [1.6, 0.2, 0.1, 0.4]) * (cl(c, { north: 1.4, temperate: 1, misty: 0.8, polar: 0.5 }) || 0),
    effects: { bite: 1.8, rare: 1.15 },
    fx: [{ id: 'tint', color: [196, 214, 204] }, { id: 'birds' }],
  },
  {
    id: 'salmon_run',
    name: 'Ход лосося',
    icon: '🐠',
    tier: 'rare',
    cat: 'fish',
    desc: 'Лосось идёт к рекам на нерест. Серебряные спины выпрыгивают из воды одна за другой.',
    duration: [90, 160],
    when: (c) => season(c, [0, 0.4, 1.8, 0.1]) * (cl(c, { north: 1.6, temperate: 0.7, misty: 1.1, polar: 0.4 }) || 0),
    effects: { rare: 1.8, bite: 1.3 },
    fx: [{ id: 'jumpers', n: 2 }],
    follow: [{ id: 'seals', chance: 0.3, delay: [10, 30] }],
  },
  {
    id: 'squid_run',
    name: 'Кальмары на свет',
    icon: '🦑',
    tier: 'uncommon',
    cat: 'fish',
    desc: 'Свет фонаря собрал кальмаров. Они кружат у борта, мерцая розовым.',
    duration: [40, 90],
    when: (c) => isNight(c) * (0.5 + (c.deep ? 0.8 : 0) + cl(c, { ocean: 0.5, misty: 0.5 })),
    effects: { bite: 1.6, rare: 1.2 },
    fx: [{ id: 'squid' }],
  },
  {
    id: 'eel_migration',
    name: 'Ход угря',
    icon: '〰️',
    tier: 'rare',
    cat: 'fish',
    desc: 'Безлунной осенней ночью угри уходят в океан. Тёмные ленты скользят под лодкой.',
    duration: [60, 120],
    when: (c) => isNight(c) * season(c, [0.2, 0.3, 1.8, 0.2]) * (0.3 + newMoon(c) * 1.5) * (cl(c, { temperate: 1, north: 1, misty: 0.8, ocean: 0.4 }) || 0),
    effects: { rare: 1.6, legendary: 1.3 },
    fx: [{ id: 'eels' }],
  },
  {
    id: 'coral_spawn',
    name: 'Нерест кораллов',
    icon: '🪸',
    tier: 'epic',
    cat: 'fish',
    desc: 'Раз в году, после полнолуния, рифы выпускают в воду облака розовых икринок. Весь риф пирует.',
    duration: [60, 120],
    when: (c) => isNight(c) * fullMoon(c) * (cl(c, { tropic: 2, ocean: 0.3 }) || 0) * season(c, [0.4, 1.2, 0.8, 0.2]),
    effects: { rare: 2.2, bite: 1.5, legendary: 1.3 },
    fx: [{ id: 'spawn' }, { id: 'tint', color: [230, 150, 170] }],
    major: true,
  },
  {
    id: 'flying_fish',
    name: 'Летучие рыбы',
    icon: '🪽',
    tier: 'uncommon',
    cat: 'fish',
    desc: 'Стайка летучих рыб планирует над волнами — за ними охотятся корифены.',
    duration: [20, 45],
    when: (c) => isDay(c) * noStorm(c) * (cl(c, { tropic: 2, ocean: 1.2 }) || 0) * warm(c),
    effects: { bite: 1.3, rare: 1.2 },
    fx: [{ id: 'flyingfish' }],
  },

  /* ═══════════ ОБИТАТЕЛИ ═══════════ */
  {
    id: 'dolphins',
    name: 'Дельфины',
    icon: '🐬',
    tier: 'uncommon',
    cat: 'life',
    desc: 'Стая дельфинов играет у борта. Говорят, они приносят удачу — и пригоняют рыбу.',
    duration: [15, 35],
    when: (c) => noStorm(c) * (1 - cold(c) * 0.8) * (c.climate === 'polar' ? 0.1 : 1),
    effects: { bite: 1.2, luck: 0.15 },
    fx: [{ id: 'dolphins' }],
  },
  {
    id: 'whale',
    name: 'Кит неподалёку',
    icon: '🐋',
    tier: 'rare',
    cat: 'life',
    desc: 'Фонтан у горизонта. Кит гонит за собой редкую рыбу.',
    duration: [30, 70],
    when: (c) => (cl(c, { ocean: 1.6, north: 1.3, polar: 1.4, misty: 1.1, temperate: 0.45, tropic: 0.6 }) || 0) * (c.deep ? 1.4 : 1),
    effects: { rare: 1.8 },
    omen: { text: 'Над водой вдалеке поднялось облачко пара…', lead: [4, 10] },
    fx: [{ id: 'whale' }],
    follow: [{ id: 'whale_song', chance: 0.35, delay: [20, 60] }],
    major: true,
  },
  {
    id: 'whale_song',
    name: 'Песнь кита',
    icon: '🎶',
    tier: 'epic',
    cat: 'life',
    desc: 'Сквозь корпус лодки слышно низкое пение. Глубинные гиганты поднимаются послушать.',
    duration: [30, 60],
    when: (c) => calm(c) * (0.4 + isNight(c)) * (c.since('whale') < 600 ? 2 : 0.15),
    effects: { legendary: 2, rare: 1.3 },
    fx: [{ id: 'bioglow', n: 0.5 }],
    chainOnly: true,
  },
  {
    id: 'orcas',
    name: 'Косатки на охоте',
    icon: '🖤',
    tier: 'epic',
    cat: 'life',
    desc: 'Стая косаток прочёсывает воду. Мелочь прячется, зато крупная рыба мечется и бросается на всё.',
    duration: [20, 45],
    when: (c) => (cl(c, { north: 1.5, polar: 1.6, ocean: 1.2, misty: 1 }) || 0) * noStorm(c),
    effects: { bite: 0.6, legendary: 1.7, rare: 1.3 },
    fx: [{ id: 'orcas' }],
    major: true,
  },
  {
    id: 'sharks',
    name: 'Плавники акул',
    icon: '🦈',
    tier: 'uncommon',
    cat: 'life',
    desc: 'Вокруг лодки режут воду треугольные плавники. Берегите улов и снасти.',
    duration: [20, 50],
    when: (c) => (cl(c, { tropic: 1.6, ocean: 1.4, misty: 0.8, temperate: 0.35 }) || 0) * warm(c),
    effects: { legendary: 1.3, gearRisk: 0.15, bite: 0.9 },
    fx: [{ id: 'fins' }],
  },
  {
    id: 'seals',
    name: 'Тюлени на камнях',
    icon: '🦭',
    tier: 'common',
    cat: 'life',
    desc: 'Тюлени греются на камнях у мыса и лениво поглядывают на ваш садок.',
    duration: [60, 140],
    when: (c) => (cl(c, { north: 1.5, polar: 1.5, temperate: 0.9, misty: 1.2 }) || 0) * noStorm(c),
    effects: { bite: 0.92, xp: 1.05 },
    fx: [{ id: 'seals' }],
  },
  {
    id: 'turtle',
    name: 'Морская черепаха',
    icon: '🐢',
    tier: 'rare',
    cat: 'life',
    desc: 'Старая черепаха всплыла подышать прямо у борта. Встретить её — к удаче.',
    duration: [12, 25],
    when: (c) => (cl(c, { tropic: 1.8, ocean: 0.8, temperate: 0.2 }) || 0) * warm(c) * calm(c),
    effects: { luck: 0.3, rare: 1.25 },
    fx: [{ id: 'turtle' }],
  },
  {
    id: 'jelly_bloom',
    name: 'Нашествие медуз',
    icon: '🪼',
    tier: 'uncommon',
    cat: 'life',
    desc: 'Тёплое течение пригнало тысячи медуз. Рыба уходит, зато за медузами приходит луна-рыба.',
    duration: [60, 150],
    when: (c) => warm(c) * calm(c) * season(c, [0.3, 1.5, 1, 0]) * (1 - cl(c, { polar: 1 })),
    effects: { bite: 0.7, rare: 1.4 },
    fx: [{ id: 'jellies' }],
  },
  {
    id: 'plankton',
    name: 'Светящийся планктон',
    icon: '✨',
    tier: 'uncommon',
    cat: 'life',
    desc: 'Море вспыхнуло голубым огнём. Каждая волна — как молния. Глубинные жители поднимаются.',
    duration: [60, 140],
    when: (c) => isNight(c) * (0.5 + warm(c)) * (1 - c.rain * 0.5),
    effects: { rare: 2 },
    fx: [{ id: 'bioglow' }],
    follow: [{ id: 'squid_run', chance: 0.25, delay: [10, 30] }],
  },
  {
    id: 'storm_petrels',
    name: 'Буревестники',
    icon: '🐦‍⬛',
    tier: 'common',
    cat: 'life',
    desc: 'Маленькие тёмные птицы скользят над самыми волнами. Старики говорят — к шторму.',
    duration: [30, 60],
    when: (c) => (1 - c.daylight * 0.3) * ss(4, 9, c.wind) * (1 - stormy(c)) * (c.cover > 0.4 ? 1.4 : 0.6),
    effects: { bite: 1.1 },
    fx: [{ id: 'petrels' }],
    follow: [{ id: 'squall', chance: 0.45, delay: [15, 40] }],
  },

  /* ═══════════ НЕБО ═══════════ */
  {
    id: 'meteor',
    name: 'Звездопад',
    icon: '☄️',
    tier: 'rare',
    cat: 'sky',
    desc: 'Небо расчерчено падающими звёздами. Загадай рыбу.',
    duration: [40, 90],
    when: (c) => isNight(c) * ss(0.25, 0.6, c.starVis) * season(c, [0.7, 1.4, 1.1, 0.9]),
    effects: { legendary: 2.5, rare: 1.5 },
    fx: [{ id: 'meteors' }],
    follow: [{ id: 'fallen_star', chance: 0.12, delay: [5, 20] }],
  },
  {
    id: 'aurora_storm',
    name: 'Пляска сияния',
    icon: '🌌',
    tier: 'epic',
    cat: 'sky',
    desc: 'Магнитная буря: сияние захватило всё небо, полотнища переливаются зелёным и фиолетовым.',
    duration: [50, 110],
    when: (c) => isNight(c) * (1 - c.cover) * (cl(c, { polar: 2, north: 1.4, misty: 0.4, temperate: 0.35, ocean: 0.3 }) || 0) * season(c, [0.8, 0.1, 1.2, 1.5]),
    effects: { rare: 1.8, legendary: 1.3 },
    atmo: { aurora: 1 },
    major: true,
  },
  {
    id: 'halo',
    name: 'Солнечное гало',
    icon: '⭕',
    tier: 'uncommon',
    cat: 'sky',
    desc: 'Вокруг солнца — радужное кольцо и два ложных солнца. Погода скоро переменится.',
    duration: [30, 70],
    when: (c) => ss(8, 20, c.sunElev) * ss(0.15, 0.4, c.cover) * (1 - ss(0.7, 0.9, c.cover)) * (0.5 + cold(c)),
    effects: { luck: 0.1, xp: 1.1 },
    fx: [{ id: 'halo' }],
  },
  {
    id: 'green_flash',
    name: 'Зелёный луч',
    icon: '💚',
    tier: 'epic',
    cat: 'sky',
    desc: 'В последний миг заката над краем солнца вспыхнула изумрудная искра. Мало кто видел её дважды.',
    duration: [3, 6],
    when: (c) => ss(-1, 0.5, c.sunElev) * (1 - ss(2, 4, c.sunElev)) * (1 - c.cover) * (1 - c.fog) * (cl(c, { ocean: 2, tropic: 1.6 }) || 0.8) * 3,
    effects: { legendary: 3, luck: 0.4 },
    fx: [{ id: 'greenflash' }],
    cooldown: 1440,
  },
  {
    id: 'moonbow',
    name: 'Лунная радуга',
    icon: '🌈',
    tier: 'legendary',
    cat: 'sky',
    desc: 'Бледная серебристая дуга в ночном небе. Лунная радуга бывает лишь после дождя в полнолуние.',
    duration: [20, 45],
    when: (c) => isNight(c) * fullMoon(c) * ss(0.2, 0.6, c.wetness) * (1 - c.rain * 2) * (1 - c.cover) * 4,
    effects: { legendary: 2.5, luck: 0.3 },
    fx: [{ id: 'moonbow' }],
  },
  {
    id: 'eclipse',
    name: 'Солнечное затмение',
    icon: '🌑',
    tier: 'mythic',
    cat: 'sky',
    desc: 'Луна закрыла солнце. Посреди дня проступили звёзды, птицы смолкли, а из глубины поднялось то, что обычно не видит света.',
    duration: [12, 22],
    when: (c) => ss(15, 30, c.sunElev) * (1 - c.cover * 0.6),
    effects: { legendary: 4, rare: 2 },
    omen: { text: 'Свет стал странным — тени заострились, вода потемнела…', lead: [4, 8] },
    fx: [{ id: 'eclipse' }],
    cooldown: 20000,
    major: true,
  },
  {
    id: 'fata_morgana',
    name: 'Фата-моргана',
    icon: '🏝️',
    tier: 'rare',
    cat: 'sky',
    desc: 'Над горизонтом повисли перевёрнутые острова и корабли, которых там нет.',
    duration: [25, 50],
    when: (c) => isDay(c) * calm(c) * (1 - c.cover) * (warm(c) + cold(c)) * (cl(c, { polar: 1.6, ocean: 1.2, tropic: 1.1, north: 1 }) || 0.6),
    effects: { rare: 1.3, xp: 1.15 },
    fx: [{ id: 'mirage' }],
  },

  /* ═══════════ ТАЙНЫ ═══════════ */
  {
    id: 'ghost_ship',
    name: 'Корабль-призрак',
    icon: '⚓',
    tier: 'legendary',
    cat: 'mystic',
    desc: 'В тумане скрипят снасти несуществующего судна… Легенды ближе.',
    duration: [25, 50],
    when: (c) => ss(0.35, 0.7, c.fog) * (0.4 + isNight(c) * 1.2),
    effects: { legendary: 4, rare: 1.5 },
    omen: { text: 'Из тумана донёсся далёкий корабельный колокол…', lead: [5, 12] },
    fx: [{ id: 'ghostship' }, { id: 'wisps', n: 0.4 }],
    major: true,
    outro: 'Корабль растаял в тумане. Был ли он вообще?',
  },
  {
    id: 'voices',
    name: 'Голоса над водой',
    icon: '🫧',
    tier: 'epic',
    cat: 'mystic',
    desc: 'Над туманной водой плывут бледные огоньки и слышится пение без слов. Не отвлекайтесь от лески.',
    duration: [20, 45],
    when: (c) => isNight(c) * ss(0.2, 0.6, c.fog + c.moonIllum * 0.3) * (0.4 + fullMoon(c)),
    effects: { legendary: 3, gearRisk: 0.2 },
    fx: [{ id: 'wisps' }],
  },
  {
    id: 'deep_lights',
    name: 'Огни в глубине',
    icon: '🔵',
    tier: 'epic',
    cat: 'mystic',
    desc: 'Из чёрной глубины медленно поднимаются светящиеся шары. Учёные спорят, кто это.',
    duration: [30, 70],
    when: (c) => isNight(c) * (c.deep ? 1.8 : 0.35) * (1 - c.waves * 0.2),
    effects: { rare: 2.4, legendary: 1.4 },
    fx: [{ id: 'deeplights' }],
  },
  {
    id: 'fallen_star',
    name: 'Упавшая звезда',
    icon: '🌠',
    tier: 'mythic',
    cat: 'mystic',
    desc: 'Огненный след прочертил небо и ушёл в воду совсем рядом. В глубине разгорается свет.',
    duration: [20, 35],
    when: (c) => isNight(c) * (c.since('meteor') < 120 ? 1 : 0),
    effects: { legendary: 5 },
    fx: [{ id: 'fallenstar' }],
    chainOnly: true,
    major: true,
    choices: [
      {
        id: 'catch',
        label: 'Подцепить сачком',
        hint: 'Свет ещё неглубоко',
        resolve: (rnd) =>
          rnd() < 0.7
            ? { text: 'В сачке — тёплый камень, мерцающий изнутри. Звёздный камень!', tone: 'good', reward: { item: 'star_stone', xp: 250 }, buff: { label: 'Звёздная удача', effects: { legendary: 1.5, luck: 0.3 }, minutes: 240 } }
            : { text: 'Свет ушёл глубже, чем казалось. Остался только запах озона.', tone: 'neutral', reward: { xp: 60 } },
      },
      {
        id: 'watch',
        label: 'Просто смотреть',
        resolve: () => ({ text: 'Вы смотрели, пока свет не погас на глубине. Такое не забывается.', tone: 'good', reward: { xp: 150 } }),
      },
    ],
  },
  {
    id: 'leviathan',
    name: 'Тень под килем',
    icon: '👁️',
    tier: 'mythic',
    cat: 'mystic',
    desc: 'Под лодкой медленно проплыла тень длиной с пирс. Леска дрогнула сама собой.',
    duration: [8, 16],
    when: (c) => (c.deep ? 1.6 : 0.25) * (cl(c, { ocean: 1.4 }) || 1) * (0.5 + isNight(c)),
    effects: { legendary: 6, rare: 1.5 },
    fx: [{ id: 'leviathan' }],
    cooldown: 6000,
    major: true,
  },

  /* ═══════════ СТИХИЯ ═══════════ */
  {
    id: 'squall',
    name: 'Шквал',
    icon: '🌪️',
    tier: 'uncommon',
    cat: 'hazard',
    desc: 'Налетел шквал: ветер рвёт гребни, хлещет дождь. Рыба бешеная, но держите снасти крепче.',
    duration: [10, 25],
    when: (c) => (1 - stormy(c)) * (0.4 + c.cover) * (c.season === 3 ? 0.4 : 1) * (cl(c, { ocean: 1.4, tropic: 1.2 }) || 1),
    effects: { bite: 1.5, gearRisk: 0.12 },
    omen: { text: 'Горизонт почернел, ветер вдруг стих…', lead: [5, 10] },
    atmo: { wind: 13, precip: 0.7, cover: 0.5, dark: 0.45, waves: 0.9 },
    fx: [{ id: 'shelf' }],
    follow: [{ id: 'rogue_wave', chance: 0.12, delay: [2, 6] }],
  },
  {
    id: 'rogue_wave',
    name: 'Волна-убийца',
    icon: '🌊',
    tier: 'epic',
    cat: 'hazard',
    desc: 'Из ниоткуда поднялась стена воды! Держитесь!',
    duration: [2, 4],
    when: (c) => ss(1.2, 2, c.waves) + stormy(c) * 0.5,
    effects: { gearRisk: 0.35, bite: 1.3 },
    fx: [],
    follow: [{ id: 'flotsam', chance: 0.5, delay: [3, 10] }],
    major: true,
    outro: 'Лодка устояла. В воде — обломки.',
  },
  {
    id: 'waterspout',
    name: 'Водяной смерч',
    icon: '🌀',
    tier: 'epic',
    cat: 'hazard',
    desc: 'Из тучи к воде опустилась крутящаяся воронка. Она идёт мимо… кажется.',
    duration: [8, 18],
    when: (c) => warm(c) * ss(0.5, 0.8, c.cover) * (cl(c, { tropic: 1.8, ocean: 1.2, temperate: 0.6 }) || 0.3) * season(c, [0.4, 1.5, 1, 0]),
    effects: { bite: 1.4, gearRisk: 0.2 },
    atmo: { wind: 6, waves: 0.4 },
    fx: [{ id: 'waterspout' }],
    major: true,
  },
  {
    id: 'st_elmo',
    name: 'Огни святого Эльма',
    icon: '🔆',
    tier: 'legendary',
    cat: 'hazard',
    desc: 'На кончике удилища и мачте зажглись голубые огни. Моряки считали их знаком покровителя.',
    duration: [8, 18],
    when: (c) => stormy(c) * 2 + (c.kind === 'downpour' ? 0.5 : 0),
    effects: { legendary: 2, luck: 0.3 },
    fx: [{ id: 'stelmo' }],
  },
  {
    id: 'fog_bank',
    name: 'Стена тумана',
    icon: '🌫️',
    tier: 'common',
    cat: 'hazard',
    desc: 'С моря накатила стена тумана. Маяк гудит, а пугливая рыба осмелела.',
    duration: [40, 100],
    when: (c) => calm(c) * (1 - c.fog) * (cl(c, { misty: 2, north: 1.3 }) || 1) * (c.hour < 10 || c.hour > 19 ? 1.4 : 0.7),
    effects: { bite: 1.2, rare: 1.1 },
    atmo: { fog: 0.7 },
    follow: [
      { id: 'ghost_ship', chance: 0.14, delay: [10, 30] },
      { id: 'voices', chance: 0.08, delay: [10, 30] },
    ],
  },
  {
    id: 'lighthouse_out',
    name: 'Маяк погас',
    icon: '🕯️',
    tier: 'rare',
    cat: 'hazard',
    desc: 'Свет маяка мигнул и погас. В темноте к лодке подходят самые пугливые рыбы.',
    duration: [20, 50],
    when: (c) => isNight(c) * (0.3 + stormy(c) + c.fog),
    effects: { rare: 1.4, gearRisk: 0.08 },
    outro: 'Смотритель починил фонарь — луч снова скользит по воде.',
  },
  {
    id: 'hail',
    name: 'Град',
    icon: '🧊',
    tier: 'uncommon',
    cat: 'hazard',
    desc: 'Ледяная крупа барабанит по борту и вскипает на воде.',
    duration: [5, 12],
    when: (c) => ss(0.5, 0.9, c.dark) * (c.temp > 3 ? 1 : 0.2) * season(c, [1, 1.3, 0.8, 0.1]),
    effects: { bite: 0.8, gearRisk: 0.1 },
    atmo: { cover: 0.3, dark: 0.2 },
    fx: [{ id: 'hail' }],
  },
  {
    id: 'drift_ice',
    name: 'Ледоход',
    icon: '🧊',
    tier: 'uncommon',
    cat: 'hazard',
    desc: 'Течение несёт льдины. Под ними держится холодолюбивая рыба.',
    duration: [80, 180],
    when: (c) => cold(c) * (cl(c, { polar: 2, north: 1.4, temperate: 0.5 }) || 0) * season(c, [1, 0, 0.4, 1.5]),
    effects: { rare: 1.3, bite: 0.85 },
    atmo: { ice: 0.7 },
  },
  {
    id: 'red_tide',
    name: 'Красный прилив',
    icon: '🟥',
    tier: 'rare',
    cat: 'hazard',
    desc: 'Цветение водорослей окрасило воду ржавчиной. Рыба вялая, а улов в порту берут неохотно.',
    duration: [120, 240],
    when: (c) => warm(c) * calm(c) * season(c, [0.2, 1.4, 1, 0]) * (cl(c, { tropic: 1.2, temperate: 1, ocean: 0.4 }) || 0.2),
    effects: { bite: 0.55, price: 0.85, rare: 1.2 },
    fx: [{ id: 'tint', color: [150, 54, 34] }],
  },

  /* ═══════════ НАХОДКИ ═══════════ */
  {
    id: 'bottle',
    name: 'Письмо в бутылке',
    icon: '🍾',
    tier: 'uncommon',
    cat: 'find',
    desc: 'У борта покачивается запечатанная бутылка. Внутри — свёрнутая бумага.',
    duration: [15, 30],
    when: (c) => noStorm(c) * (0.6 + calm(c) * 0.6),
    effects: {},
    fx: [{ id: 'bottle' }],
    choices: [
      {
        id: 'open',
        label: 'Открыть',
        resolve: (rnd): Outcome => {
          const x = rnd();
          if (x < 0.28) return { text: 'Внутри — карта с крестиком у мыса. Чернила совсем свежие…', tone: 'good', follow: 'treasure', reward: { xp: 40 } };
          if (x < 0.55) return { text: 'Монеты, завёрнутые в промасленную бумагу. Кто-то копил на лодку.', tone: 'good', reward: { money: r(rnd, 150, 520), xp: 20 } };
          if (x < 0.8) return { text: 'Стихи неизвестного рыбака о луне и сельди. Красиво, хоть и непонятно.', tone: 'good', reward: { xp: 80 }, buff: { label: 'Вдохновение', effects: { luck: 0.15 }, minutes: 120 } };
          return { text: '«Кто прочтёт — тому не будет клёва». Шутка, наверное…', tone: 'bad', buff: { label: 'Проклятие бутылки', effects: { bite: 0.8 }, minutes: 60 } };
        },
      },
      {
        id: 'release',
        label: 'Отпустить',
        hint: 'Пусть плывёт дальше',
        resolve: () => ({ text: 'Бутылка уплыла к горизонту. Море ценит вежливость.', tone: 'good', buff: { label: 'Благосклонность моря', effects: { rare: 1.2 }, minutes: 90 } }),
      },
    ],
  },
  {
    id: 'flotsam',
    name: 'Обломки на воде',
    icon: '📦',
    tier: 'uncommon',
    cat: 'find',
    desc: 'Течение принесло ящик и доски — похоже, чей-то груз смыло штормом.',
    duration: [15, 30],
    when: (c) => 0.4 + (c.since('rogue_wave') < 60 || c.since('squall') < 60 ? 3 : 0) + stormy(c) * 0.4,
    effects: {},
    fx: [{ id: 'crate' }],
    choices: [
      {
        id: 'lift',
        label: 'Поднять ящик',
        resolve: (rnd) => {
          const x = rnd();
          if (x < 0.45) return { text: 'Консервы, моток шнура и запчасти к эхолоту — продадите в порту.', tone: 'good', reward: { money: r(rnd, 220, 900) } };
          if (x < 0.8) return { text: 'Коробка светящихся приманок, почти сухая!', tone: 'good', reward: { bait: { id: 'glow', count: 3 } } };
          return { text: 'Ящик пуст, а вы занозили ладонь.', tone: 'neutral', reward: { xp: 10 } };
        },
      },
      { id: 'leave', label: 'Плыть мимо', resolve: () => ({ text: 'Обломки уплывают к мысу.', tone: 'neutral' }) },
    ],
  },
  {
    id: 'treasure',
    name: 'Тайник по карте',
    icon: '🗺️',
    tier: 'epic',
    cat: 'find',
    desc: 'По карте из бутылки вы вышли к месту, где под водой белеет что-то похожее на сундук.',
    duration: [20, 40],
    when: () => 1,
    effects: { luck: 0.2 },
    fx: [{ id: 'deeplights', n: 0.25, color: [255, 214, 140] }],
    chainOnly: true,
    major: true,
    choices: [
      {
        id: 'dive',
        label: 'Достать кошкой',
        resolve: (rnd) =>
          rnd() < 0.82
            ? { text: 'Сундук! Серебро, старинный компас и судовой журнал 1911 года.', tone: 'good', reward: { money: r(rnd, 1500, 4200), item: 'old_compass', xp: 200 } }
            : { text: 'Всего лишь ржавый якорь. Зато какой — в музей возьмут!', tone: 'neutral', reward: { money: 300, xp: 120 } },
      },
      { id: 'mark', label: 'Отметить и уйти', resolve: () => ({ text: 'Вы отметили место на карте. Может, в другой раз.', tone: 'neutral', reward: { xp: 30 } }) },
    ],
  },
  {
    id: 'ghost_net',
    name: 'Брошенная сеть',
    icon: '🕸️',
    tier: 'uncommon',
    cat: 'find',
    desc: 'Дрейфующая сеть-призрак, в ней бьётся рыба.',
    duration: [15, 30],
    when: (c) => noStorm(c) * 0.8,
    effects: {},
    fx: [{ id: 'net' }],
    choices: [
      {
        id: 'free',
        label: 'Освободить рыбу',
        resolve: () => ({ text: 'Вы распутали сеть и выпустили дюжину рыб. Море помнит добро.', tone: 'good', reward: { xp: 90 }, buff: { label: 'Благодарность моря', effects: { rare: 1.4, luck: 0.15 }, minutes: 120 } }),
      },
      { id: 'take', label: 'Забрать сеть', resolve: (rnd) => ({ text: 'Сеть пригодится в хозяйстве. Рыбе в ней повезло меньше.', tone: 'neutral', reward: { money: r(rnd, 80, 200) } }) },
    ],
  },

  /* ═══════════ ЛЮДИ ═══════════ */
  {
    id: 'rival',
    name: 'Соперник',
    icon: '🎣',
    tier: 'uncommon',
    cat: 'people',
    desc: 'Старик Сёмин на своей «Ласточке» встал неподалёку и кричит: «Спорим, моя рыба будет больше?»',
    duration: [20, 40],
    when: (c) => noStorm(c) * (0.4 + c.daylight) * (1 - c.fog),
    effects: { bite: 0.95 },
    fx: [{ id: 'boat', variant: 'rival' }],
    choices: [
      {
        id: 'accept',
        label: 'Принять спор',
        hint: 'Ставка 150 ₽',
        resolve: (rnd) =>
          rnd() < 0.55
            ? { text: 'Ваша рыба тяжелее! Сёмин платит и делится байками про «хозяина бухты».', tone: 'good', reward: { money: 150, xp: 60 }, buff: { label: 'Кураж', effects: { bite: 1.2 }, minutes: 45 } }
            : { text: 'Его щука оказалась на полкило тяжелее. Минус 150 ₽, плюс опыт.', tone: 'bad', reward: { money: -150, xp: 40 } },
      },
      { id: 'decline', label: 'Махнуть рукой', resolve: () => ({ text: '«Эх, молодёжь!» — Сёмин уходит к мысу.', tone: 'neutral' }) },
    ],
  },
  {
    id: 'trader',
    name: 'Плавучая лавка',
    icon: '🛶',
    tier: 'rare',
    cat: 'people',
    desc: 'К вам подошла лодка-лавка под полосатым тентом: наживки, байки и «очень редкие карты».',
    duration: [20, 40],
    when: (c) => noStorm(c) * (0.3 + c.daylight) * (1 - c.fog * 0.5),
    effects: {},
    fx: [{ id: 'boat', variant: 'trader' }],
    choices: [
      { id: 'glow', label: 'Светящиеся приманки', hint: '6 шт. за 900 ₽', resolve: () => ({ text: 'Шесть светящихся приманок — дешевле, чем в порту.', tone: 'good', reward: { money: -900, bait: { id: 'glow', count: 6 } } }) },
      {
        id: 'map',
        label: 'Купить карту',
        hint: '400 ₽, без гарантий',
        resolve: (rnd) =>
          rnd() < 0.55
            ? { text: 'Карта выглядит настоящей. Крестик — совсем рядом.', tone: 'good', reward: { money: -400 }, follow: 'treasure' }
            : { text: 'На обороте карты — меню трактира. Вас надули.', tone: 'bad', reward: { money: -400 } },
      },
      { id: 'pass', label: 'Не сегодня', resolve: () => ({ text: 'Лавка уходит, позвякивая колокольчиком.', tone: 'neutral' }) },
    ],
  },
  {
    id: 'distress',
    name: 'Сигнал бедствия',
    icon: '🆘',
    tier: 'rare',
    cat: 'people',
    desc: 'Над водой взлетела красная ракета. Кто-то в беде.',
    duration: [15, 30],
    when: (c) => (0.3 + stormy(c) * 1.5 + c.fog) * (0.4 + c.night),
    effects: { bite: 0.9 },
    fx: [{ id: 'flare' }],
    major: true,
    choices: [
      {
        id: 'help',
        label: 'Идти на помощь',
        hint: 'Потеряете время',
        resolve: () => ({ text: 'Вы сняли с мели лодку двух рыбаков из Нордхавна. Они обещали не забыть.', tone: 'good', reward: { xp: 220 }, follow: 'gratitude' }),
      },
      { id: 'radio', label: 'Вызвать береговую охрану', resolve: () => ({ text: 'Береговая охрана приняла вызов и уже в пути.', tone: 'neutral', reward: { xp: 50 } }) },
    ],
  },
  {
    id: 'gratitude',
    name: 'Благодарность спасённых',
    icon: '🤝',
    tier: 'rare',
    cat: 'people',
    desc: 'Весть о спасении разошлась по портам: торговцы платят больше, а рыбаки делятся секретными местами.',
    duration: [300, 600],
    when: () => 1,
    effects: { price: 1.15, xp: 1.2, rare: 1.15 },
    chainOnly: true,
  },
  {
    id: 'festival',
    name: 'Праздник в посёлке',
    icon: '🎆',
    tier: 'rare',
    cat: 'people',
    desc: 'В посёлке у маяка праздник: над мысом салют, а в порту рыбу берут втридорога.',
    duration: [60, 120],
    when: (c) => ss(-6, 0, -c.sunElev) * noStorm(c) * (1 - c.rain) * season(c, [0.6, 1.6, 0.8, 0.9]) * (c.hour > 19 || c.hour < 1 ? 1.6 : 0.2),
    effects: { price: 1.3, xp: 1.1 },
    fx: [{ id: 'fireworks' }],
  },
  {
    id: 'regatta',
    name: 'Регата',
    icon: '⛵',
    tier: 'uncommon',
    cat: 'people',
    desc: 'По горизонту идут парусники — местная регата. Шумно, но красиво.',
    duration: [60, 120],
    when: (c) => isDay(c) * ss(3, 6, c.wind) * (1 - ss(11, 15, c.wind)) * season(c, [0.6, 1.6, 0.7, 0]) * (1 - c.rain),
    effects: { bite: 0.9, xp: 1.1 },
    fx: [{ id: 'sails' }],
  },
];

export const EVENT_BY_ID: Record<string, EventDef> = Object.fromEntries(EVENTS.map((e) => [e.id, e]));

/** Подписи эффектов для интерфейса */
export function effectChips(e: Partial<Record<keyof import('./types').EventEffects, number>>) {
  const out: { label: string; good: boolean }[] = [];
  const mul = (k: keyof typeof e, name: string, inv = false) => {
    const v = e[k];
    if (v === undefined || v === 1) return;
    out.push({ label: `${name} ×${+v.toFixed(2)}`, good: inv ? v < 1 : v > 1 });
  };
  mul('bite', 'Клёв');
  mul('rare', 'Редкие');
  mul('legendary', 'Легенды');
  mul('price', 'Цены');
  mul('xp', 'Опыт');
  if (e.luck) out.push({ label: `Удача +${Math.round(e.luck * 100)}%`, good: true });
  if (e.gearRisk) out.push({ label: `Риск снастей +${Math.round(e.gearRisk * 100)}%`, good: false });
  return out;
}

export { twilight };
