import type { EventDef } from "./types";
import { EVENTS as RELEASE_EVENTS } from "./catalog";

/** Small compatibility layer for legacy events that had no direct Ysys entry. */
const LEGACY_EVENTS: EventDef[] = [
  {
    id: "calm",
    name: "Мёртвый штиль",
    icon: "〰️",
    tier: "uncommon",
    cat: "hazard",
    desc: "Ни ветерка. Рыба затаилась, но терпеливых ждёт крупная.",
    duration: [120, 120],
    when: (c) => (c.weather === "clear" ? 0.55 : 0),
    effects: { bite: 0.6, rare: 2.2 },
    atmo: { wind: -1.5 },
  },
  {
    id: "rainbow",
    name: "Радуга",
    icon: "🌈",
    tier: "rare",
    cat: "sky",
    desc: "После дождя над водой встала радуга. Говорят, под ней клюют редкие рыбы.",
    duration: [90, 90],
    when: () => 0,
    chainOnly: true,
    effects: { rare: 1.6, bite: 1.2 },
  },
  {
    id: "calving",
    name: "Откол ледника",
    icon: "🧊",
    tier: "rare",
    cat: "hazard",
    desc: "От шельфа с грохотом отошла глыба. Волна подняла со дна корм — рыба оживилась.",
    duration: [80, 80],
    when: (c) => (c.loc === "antarctic" ? 0.35 : 0),
    effects: { bite: 1.8, rare: 1.3 },
    atmo: { waves: 0.25 },
    fx: [{ id: "shelf" }],
  },
  {
    id: "eruption",
    name: "Подводное извержение",
    icon: "🌋",
    tier: "epic",
    cat: "hazard",
    desc: "Над кальдерой поднимается пар. Глубинные виды выходят к поверхности.",
    duration: [100, 100],
    when: (c) => (c.loc === "volcano" ? 0.28 : 0),
    effects: { rare: 2.2 },
    atmo: { fog: 0.08, cover: 0.06 },
    fx: [{ id: "wisps" }],
  },
  {
    id: "spawnrun",
    name: "Ход рыбы",
    icon: "🐟",
    tier: "uncommon",
    cat: "fish",
    desc: "Косяки идут из моря в реку на нерест. Вода в протоках живая.",
    duration: [150, 150],
    when: (c) => (["estuary", "skerries"].includes(c.loc ?? "") && (c.season === 0 || c.season === 2) ? 0.45 : 0),
    effects: { bite: 2 },
    fx: [{ id: "boil" }],
  },
  {
    id: "tide",
    name: "Большой прилив",
    icon: "🌊",
    tier: "uncommon",
    cat: "hazard",
    desc: "Вода заливает корни и отмели. Хищники заходят кормиться.",
    duration: [120, 120],
    when: (c) => (["mangrove", "estuary"].includes(c.loc ?? "") ? 0.45 : 0),
    effects: { bite: 1.5, rare: 1.4 },
    atmo: { waves: 0.12 },
    fx: [{ id: "current" }],
  },
];

export const GAME_EVENTS: EventDef[] = [...RELEASE_EVENTS, ...LEGACY_EVENTS];
export const GAME_EVENT_BY_ID = Object.fromEntries(GAME_EVENTS.map((e) => [e.id, e])) as Record<string, EventDef>;
